### PR TITLE
Add vast-trunk compiler

### PR DESCRIPTION
**Pull request by xlauko**
## Goal

Provide Compiler Explorer functionality to facilitate experimentation with VAST,
an MLIR frontend for C/C++, based on the clang tooling.

## Presumed info needed to move forward

VAST serves as an experimental frontend, generating a stack of IRs 
based on MLIR (https://trailofbits.github.io/vast/), akin
to ClangIR. While leveraging most of the Clang infrastructure, it introduces a
custom frontend. By integrating with Compiler Explorer, we can inspect MLIR
files and experiment with the currently supported C/C++ languages.

It would be great if we can incorporate support for our project, thanks! :)

## Pull Requests

I have already created 2 PRs based on previous integrations:
infra: https://github.com/compiler-explorer/infra/pull/1209
compiler-explorer: https://github.com/compiler-explorer/compiler-explorer/pull/5973

### CODE REVIEW

**Comment by xlauko** [comment]
At the moment, I am getting an error of missing shared  library dependency: `libclang-cpp.so.17`. Is there way to provide LD_LIBRARY_PATH to it? Is it already present somewhere in CE?

**Comment by xlauko** [comment]
I tried to utilize our trunk release from GitHub builds, but it might be that it is not the optimal choice. Should provide a custom build at https://github.com/compiler-explorer/misc-builder instead, or is this approach ok?

**Comment by mattgodbolt** [comment]
Re: the missing dependencies; if this needs system dependencies (e.g. clang et al) we usually build them ourselves.

I think if you could do a build in the misc-builder (I can help!) that would be ideal; OR we point this install at the clang install we know we have (if there's a way to rewrite rpaths etc). Let me know :)

**Comment by xlauko** [comment]
> I think if you could do a build in the misc-builder (I can help!) that would be ideal; OR we point this install at the clang install we know we have (if there's a way to rewrite rpaths etc). Let me know :)

I'm open to any of those. My initial attempt was aimed at reducing your build times, but the decision is ultimately yours. :)

**Comment by xlauko** [comment]
Where can I point vast to find built `libclang-cpp.so.17`?

**Comment by mattgodbolt** [comment]
> I'm open to any of those. My initial attempt was aimed at reducing your build times, but the decision is ultimately yours. :)

Appreciated - it's an easyish option though

> @mattgodbolt where can I point vast to find built libclang-cpp.so.17?

@xlauko Good question: we can make a dependency on clang 17 and then, how might the installer be pointed at it? `patchelf` maybe?

I'll take a look at what I can get working!

**Comment by mattgodbolt** [comment]
Well, annoyingly our `clang` is built statically, so no libLLVM there, and our `libraries/llvm` doesn't have a built binary in a place I can easily get to. So, I'm going to take a look at some options.

**Comment by xlauko** [comment]
> @xlauko Good question: we can make a dependency on clang 17 and then, how might the installer be pointed at it? patchelf maybe?

I think setting `LD_LIBRARY_PATH` to point to clang libraries should do the trick.
But if it's too complex I can provide custom build.

**Comment by mattgodbolt** [comment]
It's not tricky. We tend to ship all the deps needed in our tarball, and use `rpath` with `$ORIGIN`

Right now I'm having trouble building, following the insturctions on https://trailofbits.github.io/vast/GettingStarted/build/

First, seems like I need `lld` so I installed that too.

Now:
```
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Install prefix: /usr/local
-- Performing Test HAVE_FFI_CALL
-- Performing Test HAVE_FFI_CALL - Success
-- Found FFI: /usr/lib/x86_64-linux-gnu/libffi.so  
-- Could NOT find LibEdit (missing: LibEdit_INCLUDE_DIRS LibEdit_LIBRARIES) 
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib/x86_64-linux-gnu/libtinfo.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")  
-- Could NOT find zstd (missing: zstd_LIBRARY zstd_INCLUDE_DIR) 
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.13") 
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
CMake Error at /usr/lib/llvm-17/lib/cmake/clang/ClangTargets.cmake:827 (message):
  The imported target "clangBasic" references the file

     "/usr/lib/llvm-17/lib/libclangBasic.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/llvm-17/lib/cmake/clang/ClangTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/llvm-17/lib/cmake/clang/ClangConfig.cmake:20 (include)
  CMakeLists.txt:85 (find_package)

```

I installed clang17 and llvm using llvm's own "install a llvm" script:
```
RUN bash -c "$(curl -s -o - https://apt.llvm.org/llvm.sh)" 17
```

Any ideas?

**Comment by mattgodbolt** [comment]
maybe need to install `lit` or something?

**Comment by mattgodbolt** [comment]
ah I'm missing a `--recursive` on the git

**Comment by mattgodbolt** [comment]
It's now getting to building but...
```
/root/vast-trunk-20240115/include/vast/Util/DataLayout.hpp: In member function 'bool vast::dl::DataLayoutBlueprint::try_emplace(vast::mlir_type, const clang::Type*, const acontext_t&)':
/root/vast-trunk-20240115/include/vast/Util/DataLayout.hpp:105:30: error: useless cast to type 'uint32_t' {aka 'unsigned int'} [-Werror=useless-cast]
  105 |             auto abi_align = static_cast< uint32_t >(info.Align);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-gnu-zero-variadic-macro-arguments' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-unreachable-code-return' may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors
[92/179] Building CXX object lib/vast/Dialect/Core/CMakeFiles/VASTCore.dir/Release/Linkage.cpp.o
FAILED: lib/vast/Dialect/Core/CMakeFiles/VASTCore.dir/Release/Linkage.cpp.o 
/usr/bin/c++ -DGAP_ENABLE_COROUTINES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCMAKE_INTDIR=\"Release\" -I/usr/lib/llvm-17/include -I/root/vast-trunk-20240115/include -I/root/vast-trunk-20240115/builds/ninja-multi-default/include -I/root/vast-trunk-20240115/external/gap/core/include -I/root/vast-trunk-20240115/external/gap/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -std=c++20   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wno-unreachable-code-return -Wno-gnu-zero-variadic-macro-arguments -Werror -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wuseless-cast -MD -MT lib/vast/Dialect/Core/CMakeFiles/VASTCore.dir/Release/Linkage.cpp.o -MF lib/vast/Dialect/Core/CMakeFiles/VASTCore.dir/Release/Linkage.cpp.o.d -o lib/vast/Dialect/Core/CMakeFiles/VASTCore.dir/Release/Linkage.cpp.o -c /root/vast-trunk-20240115/lib/vast/Dialect/Core/Linkage.cpp
In file included from /usr/lib/llvm-17/include/clang/Basic/TargetInfo.h:29,
                 from /root/vast-trunk-20240115/lib/vast/Dialect/Core/Linkage.cpp:6:
/usr/lib/llvm-17/include/llvm/ADT/SmallSet.h: In instantiation of 'llvm::SmallSetIterator<T, N, C>::~SmallSetIterator() [with T = int; unsigned int N = 4; C = std::less<int>]':
/usr/include/c++/11/bits/stl_pair.h:211:12:   required from here
/usr/lib/llvm-17/include/llvm/ADT/SmallSet.h:59:5: error: this condition has identical branches [-Werror=duplicated-branches]
   59 |     if (isSmall)
      |     ^~
```

**Comment by mattgodbolt** [comment]
I'll check in where I'm up to for comment so you can see what I'm doing and maybe help

**Comment by mattgodbolt** [comment]
looks like it may be building with the wrong compiler; I'll assume it should be built with the clang we just installed :)_

**Comment by xlauko** [comment]
Any c++20-capable compiler should work, so this is problem on our end. I will fix it tomorrow. 
You can push somewhere the build script you have started. I can continue from here :)

**Comment by mattgodbolt** [comment]
L:ooks like it's building ok with clang-17 (instead of system-default gcc on 22.04). I'll try and get this all finished and uploaded soon! :)

**Comment by mattgodbolt** [comment]
I just pushed the fix (I had to take a long call, and have lunch). Hope to get it built and installed shortly :)

**Comment by mattgodbolt** [comment]
Built and now installing...

**Pull request merged**
