### PR TITLE
Add nsimd version 3.0.1

### PR DESCRIPTION
**Pull request by JDPailleux**

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks for this! Is there any way we can move this to our more standard library system, or is this very special case? It looks like it's building things which makes it a little unusual, so maybe this is the right place. Either way; can you resolve the conflict please? thanks!

**Comment by partouf** [comment]
This failed at some point during installation, the tail of it is
```
+ make install
mkdir -p /opt/compiler-explorer/libs/nsimd/v3.0.1/x86_64/lib
cp -f libnsimd_avx512_skylake.so /opt/compiler-explorer/libs/nsimd/v3.0.1/x86_64/lib
mkdir -p /opt/compiler-explorer/libs/nsimd/v3.0.1/x86_64/include
cp -rf /tmp/nsimd/nsimd/build/../include/nsimd /opt/compiler-explorer/libs/nsimd/v3.0.1/x86_64/include
mkdir -p /opt/compiler-explorer/libs/nsimd/v3.0.1/x86_64/doc 
cp -rf /tmp/nsimd/nsimd/build/../doc/html /opt/compiler-explorer/libs/nsimd/v3.0.1/x86_64/doc
+ export PATH=/opt/compiler-explorer/cuda/9.1.85/bin:/opt/compiler-explorer/gcc-6.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/compiler-explorer/cmake/bin
+ PATH=/opt/compiler-explorer/cuda/9.1.85/bin:/opt/compiler-explorer/gcc-6.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/compiler-explorer/cmake/bin
+ ../nstools/bin/nsconfig .. -Dsimd=cuda -prefix=/opt/compiler-explorer/libs/nsimd/v3.0.1/cuda -Ggnumake -Dstatic_libstdcpp=true -suite=cuda
update_compilers/install_libraries.sh: line 277: ../nstools/bin/nsconfig: No such file or directory
```

**Comment by partouf** [comment]
so that's here https://github.com/compiler-explorer/infra/pull/618/files#diff-b81ddda1a3ef720c264074479652c1f330e498c2ef58875447d3e7a595d2fdfcR277

**Comment by partouf** [comment]
there's no bin folder there
```
Oct/30 14:39 admin-node/t/n/n/build ((v3.0.1)|✔) 1.2m $ ls -l ../nstools/
total 64
-rw-r--r-- 1 root root  1057 Oct 30 14:21 LICENSE
-rw-r--r-- 1 root root 29500 Oct 30 14:21 README.md
drwxr-xr-x 2 root root  4096 Oct 30 14:21 http2s/
drwxr-xr-x 2 root root  4096 Oct 30 14:21 installation-scripts/
drwxr-xr-x 2 root root  4096 Oct 30 14:21 monitoring/
drwxr-xr-x 7 root root  4096 Oct 30 14:21 ns2/
drwxr-xr-x 3 root root  4096 Oct 30 14:24 nsconfig/
drwxr-xr-x 2 root root  4096 Oct 30 14:21 sshjob/
drwxr-xr-x 4 root root  4096 Oct 30 14:21 timetable/
```

**Comment by partouf** [comment]
nsconfig is in the nsconfig folder

**Comment by partouf** [comment]
Fixed and installed. But still need to add these libs to the website itself

**Comment by JDPailleux** [comment]
Thank you very much, I will launch a Pull Request on compiler explorer. 
I actually forgot this step.
Thanks again.

**Pull request merged**
