### PR TITLE
Support default EDG compilers

### PR DESCRIPTION
**Pull request by mattgodbolt**
CC @DarkArc this is my plan for EDG default...is there anything missing do you think? It creates a default script:

```
$ cat /opt/compiler-explorer/edg-6.5-default-13/eccp-scripts/eccp-default
#!/bin/bash
set -euo pipefail

export EDG_INSTALL_DIR="/opt/compiler-explorer/edg-6.5-default-13"
export EDG_C_TO_OBJ_COMPILER="/opt/compiler-explorer/gcc-13.2.0/bin/default"

# Set environment variables related to the compiler explorer configuration.
export EDG_BASE="$EDG_INSTALL_DIR/bases/default"

export CPFE="$EDG_INSTALL_DIR/bin/cpfe"
export ECCP_LIBDIR="$EDG_INSTALL_DIR/lib"
export EDG_MUNCH_PATH="$EDG_INSTALL_DIR/bin/edg_munch"
export EDG_DECODE_PATH="$EDG_INSTALL_DIR/bin/edg_decode"
export EDG_PRELINK_PATH="$EDG_INSTALL_DIR/bin/edg_prelink"
export ECCP="$EDG_INSTALL_DIR/bin/eccp"
export EDG_RUNTIME_LIB="edgrt"


# Execute the real eccp driver script.
exec "$EDG_INSTALL_DIR/bin/eccp" $@
```

### CODE REVIEW

**Comment by DarkArc** [comment]
Looks good to me :)

**Comment by mattgodbolt** [comment]
This is now live :)

**Comment by DarkArc** [comment]
Hm... It seems something isn't quite right... https://godbolt.org/z/EPdsc6drx

It looks like this GCC doesn't exist?

```
export EDG_C_TO_OBJ_COMPILER="/opt/compiler-explorer/gcc-13.2.0/bin/default"
```

That's not making much sense to me as both use the same compiler?

**Comment by mattgodbolt** [comment]
good point! fixing

**Comment by mattgodbolt** [comment]
for "default" I assume gcc still? I don't get what "default" means in this context or why it still is "default, but GCC" - does that need to be called out somewhere?

**Comment by partouf** [comment]
looks to me it should be `export EDG_C_TO_OBJ_COMPILER="/opt/compiler-explorer/gcc-13.2.0/bin/gcc"`, right?

**Comment by mattgodbolt** [comment]
yeah I'm fixing it now. but I'm just having a confusion over why it needs a GCC at all and whether we need to label this "EDG defult (gcc)" or something in the other repo. will let @DarkArc decide on that front but fixing the path now.

**Comment by mattgodbolt** [comment]
a65285f4746c60ed57c64e04922e4b646405ccad

**Comment by DarkArc** [comment]
Really... I'm not sure we need to mention the GCC.

The EDG front end -- as there's currently no built-in support for emitting any kind of IR (e.g., llvm) and/or any kind of assembler -- emits C. GCC in this context is basically used to compile that C into an executable.

How about we change the label "EDG-DEFAULT" to "EDG" and the label for this specific instance to "EDG 6.5". Really, the fact that GCC is being used is an implementation detail roughly as relevant as what linker is being used.

**Comment by mattgodbolt** [comment]
Got it! Of course I forgot that it doesn't compile. I'm sorry again!

**Pull request merged**
