### PR TITLE
kokkos `4.2.00`

### PR DESCRIPTION
**Pull request by cz4rs**
Add [the latest kokkos release](https://github.com/kokkos/kokkos/releases/tag/4.2.00).

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Looks like these aren't installing correctly:
```
Installing libraries/c++/kokkos 4.0.01
2023-11-22 22:58:00,346 lib.installation_context INFO     Fetching https://github.com/kokkos/kokkos/archive/4.0.01.tar.gz (0 bytes)
2023-11-22 22:58:00,631 lib.installation_context INFO     100% of https://github.com/kokkos/kokkos/archive/4.0.01.tar.gz
2023-11-22 22:58:00,631 lib.installation_context INFO     Piping to tar zxf -
2023-11-22 22:58:31,308 lib.installation_context INFO     Moving from staging (/opt/compiler-explorer/staging/f791ce7e-6498-4772-be10-9d98d8404b16/kokkos-4.0.01) to final destination (/opt/compiler-explorer/libs/kokkos/4.0.01)
2023-11-22 22:58:36,365 lib.installation_context INFO     Destination /opt/compiler-explorer/libs/kokkos/4.0.01 exists, temporarily moving out of the way (to /opt/compiler-explorer/staging/f791ce7e-6498-4772-be10-9d98d8404b16.orig)
2023-11-22 22:58:36,382 lib.installation_context INFO     Removing temporarily moved /opt/compiler-explorer/staging/f791ce7e-6498-4772-be10-9d98d8404b16.orig
2023-11-22 22:58:43,673 lib.ce_install  ERROR    libraries/c++/kokkos 4.0.01 installed OK, but doesn't appear as installed after
...
2023-11-22 23:00:06,754 lib.ce_install  ERROR    libraries/c++/kokkos 4.2.00 installed OK, but doesn't appear as installed after
0 packages installed OK, 0 skipped, and 3 failed installation
Failed:
  libraries/c++/kokkos 4.0.01
  libraries/c++/kokkos 4.1.00
  libraries/c++/kokkos 4.2.00

```

I'll try and work out what's going on.

**Comment by mattgodbolt** [comment]
Fixed in eb5b827a

**Comment by cz4rs** [comment]
> Fixed in [eb5b827](https://github.com/compiler-explorer/infra/commit/eb5b827a508740ee07d6e8e056b4cdb321272ff8)

Great! Thanks for catching this quickly 🙂

**Comment by mattgodbolt** [comment]
this should be live now :)

**Pull request merged**
