### PR TITLE
Add CUDA 11 and 11 Update 1

### PR DESCRIPTION
**Pull request by jrhemstad**

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks for these! Will manually run the installer straight after.

**Comment by mattgodbolt** [comment]
Hi @jrhemstad !

I just tried installing but it seems the CUDA directory layout has changed, and the shell scripts no longer work. Will investigate:

```
+ curl -s -L https://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda_11.0.2_450.51.05_linux.run -o /tmp/tmp.cWukt0ARUd
+ cat /tmp/tmp.cWukt0ARUd
+ rm /tmp/tmp.cWukt0ARUd
+ sh /opt/compiler-explorer/tmp/cuda/combined.sh --extract=/opt/compiler-explorer/tmp/cuda
++ ls -1 '/opt/compiler-explorer/tmp/cuda/cuda-linux.11.0.2*.run'
++ true
+ local LINUX=
+ [[ -f '' ]]
+ mv /opt/compiler-explorer/tmp/cuda/cuda-toolkit /opt/compiler-explorer/cuda/11.0.2
mv: cannot stat '/opt/compiler-explorer/tmp/cuda/cuda-toolkit': No such file or directory
root@admin-node:/home/ubuntu/infra# ls /opt/compiler-explorer/tmp/cuda/
EULA.txt                           cuda_demo_suite     cuda_nvml_dev  cuda_sanitizer_api  libnpp
NVIDIA-Linux-x86_64-450.51.05.run  cuda_documentation  cuda_nvprof    integration         libnvjpeg
bin                                cuda_gdb            cuda_nvprune   libcublas           nsight_compute
combined.sh                        cuda_memcheck       cuda_nvrtc     libcufft            nsight_systems
cuda_cudart                        cuda_nsight         cuda_nvtx      libcurand
cuda_cuobjdump                     cuda_nvcc           cuda_nvvp      libcusolver
cuda_cupti                         cuda_nvdisasm       cuda_samples   libcusparse
```

**Comment by mattgodbolt** [comment]
I think I'm going to have to look at this later: the install script is a bit out of date, and ideally I'll port it to the new installation mechanism! Sorry for the delay!

**Comment by mattgodbolt** [comment]
I had a quick sketch, and it's not clear to me what parts we need. Previous directories look like:

```
root@admin-node:/home/ubuntu/infra# ls /opt/compiler-explorer/cuda/10.2.89
EULA.txt  extras   libnsight                nsight-systems-2019.5.2  nvvm   src      version.txt
bin       include  libnvvp                  nsightee_plugins         nvvmx  targets
doc       lib64    nsight-compute-2019.5.0  nvml                     share  tools
root@admin-node:/home/ubuntu/infra# ls /opt/compiler-explorer/cuda/10.1.
10.1.105/ 10.1.168/ 10.1.243/ 
root@admin-node:/home/ubuntu/infra# ls /opt/compiler-explorer/cuda/10.1.243
EULA.txt  extras   libnsight                nsight-systems-2019.3.7.5  nvvm   targets
bin       include  libnvvp                  nsightee_plugins           share  tools
doc       lib64    nsight-compute-2019.4.0  nvml                       src    version.txt
```

I tried installing with NVidia-*.run but that tried to install kernel drivers and doesn't support `--prefix` any more.

The output looks like:

```
root@admin-node:/home/ubuntu/infra# ls /opt/compiler-explorer/tmp/cuda/
EULA.txt                           cuda_demo_suite     cuda_nvml_dev  cuda_sanitizer_api  libnpp
NVIDIA-Linux-x86_64-450.51.05.run  cuda_documentation  cuda_nvprof    integration         libnvjpeg
bin                                cuda_gdb            cuda_nvprune   libcublas           nsight_compute
combined.sh                        cuda_memcheck       cuda_nvrtc     libcufft            nsight_systems
cuda_cudart                        cuda_nsight         cuda_nvtx      libcurand
cuda_cuobjdump                     cuda_nvcc           cuda_nvvp      libcusolver
cuda_cupti                         cuda_nvdisasm       cuda_samples   libcusparse
```

and the nearest equivalent that I could see to before is cuda_nvcc:

```
root@admin-node:/home/ubuntu/infra# ls -l /opt/compiler-explorer/tmp/cuda/cuda_nvcc/
total 16
drwxr-xr-x 3 root root 6144 Sep 22 13:13 bin
lrwxrwxrwx 1 root root   28 Sep 22 13:13 include -> targets/x86_64-linux/include
drwxr-xr-x 7 root root 6144 Sep 22 13:13 nvvm
drwxr-xr-x 3 root root 6144 Sep 22 13:13 targets
```
but that's missing stuff?

I guess we can take the whole output directory and then at least we aren't missing anything. Advice welcomed!

**Comment by partouf** [comment]
So the files we need/use are:
* nvcc
* nvdisasm
* ptxas

**Comment by jrhemstad** [comment]
My apologies. I didn't realize that they had reorganized the install directory so significantly. 

I pulled down the CUDA 11 .run file and I'm having a look at the contents. 

> So the files we need/use are:
> 
> * nvcc
> * nvdisasm
> * ptxas

The paths to these things are:
- `cuda_nvcc/bin/nvcc`
- `cuda_nvdisasm/bin/nvdisasm`
- `cuda_nvcc/bin/ptxas`

> I tried installing with NVidia-*.run but that tried to install kernel drivers and doesn't support --prefix any more.

If you want to just run the installer, you should be able to do:

```
./cuda_11.0.2_450.51.05_linux.run --silent --toolkit --toolkitpath=<path>
```

That will avoid trying to install the drivers.

**Comment by jrhemstad** [comment]
Let me know how I can help or what you all think is the right solution here.

**Comment by mattgodbolt** [comment]
Thanks @jrhemstad ! I should be able to muddle something through. Looks like we can avoid the run entirely and "just" copy the whole directory, though I'll give the run a go first.

**Pull request merged**
