### PR TITLE
LLVM 11

### PR DESCRIPTION
**Pull request by ojeda**
Note: untested.
See: https://github.com/compiler-explorer/compiler-explorer/pull/2273

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks for this!  For future reference, if you'd like to test locally:

```
$ make ce  # this is a one time setup
$ ./bin/ce_install install llvm 11.0.0
```

(assuming you can write to `/opt/compiler-explorer/`, the default install location. If that's not writeable, `--dest SOMEPATH` will install there instead!)

Right now we build and fetch our own clangs, so this is failing as `clang-11.0.0.tar.xz` hasn't (yet) been built.

We haven't built clang and llvm 11.0.0 as it hasn't yet been released; it's still in RC mode; though it seems like it'll be ready very soon (rc5 came out 10 days ago, but no final build yet).

**Comment by ojeda** [comment]
Yeah, that is why I set the PR as draft -- I didn't mean to use your time :-)

**Comment by mattgodbolt** [comment]
Got it!! Thanks :D This will be all ready once the release is made: thank you!

**Comment by ojeda** [comment]
No, thanks to *you* for the time you take replying with precise details! (and apologies for having wasted it :-)

**Comment by mattgodbolt** [comment]
```
$ /opt/compiler-explorer/clang-11.0.0/bin/clang --version
clang version 11.0.0 (https://github.com/llvm/llvm-project.git 176249bd6732a8044d457092ed932768724a6f06)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-11.0.0/bin
```
yay

**Pull request merged**
