### PR TITLE
add v2.0.0 version of scnlib (c++)

### PR DESCRIPTION
**Pull request by correaa**

### CODE REVIEW

**Comment by partouf** [comment]
Can you also submit a PR to add the new version to this file: https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L4237

**Comment by correaa** [comment]
yes, thanks, I forgot that part of the protocol

**Comment by correaa** [comment]
here it is https://github.com/compiler-explorer/compiler-explorer/pull/6121

**Review by mattgodbolt — APPROVED** [review]

**Comment by correaa** [comment]
since it didn't link, I am trying this: https://github.com/compiler-explorer/infra/pull/1235

**Pull request merged**
