### PR TITLE
Changed snowball to version 0.1.0

### PR DESCRIPTION
**Pull request by mauro-balades**

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
so long as you're happy to keep forgetting about old compilers, I'm happy to merge.

**Comment by mattgodbolt** [comment]
Hi @mauro-balades unfortunately this built version of snowball needs an SSL library not available on Compiler Explorer:

```
2024-01-15 17:55:01,612 lib.installation_context INFO     Moving from staging (/opt/compiler-explorer/staging/11efa66b-4304-4a7f-b2ea-be9573bd144f/snowball-0.1.0) to final destination (/opt/compiler-explorer/snowball-0.1.0)
/opt/compiler-explorer/snowball-0.1.0/bin/snowball: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
2024-01-15 17:55:01,937 lib.ce_install  ERROR    compilers/snowball 0.1.0 installed OK, but doesn't appear as installed after
0 packages installed OK, 0 skipped, and 1 failed installation
```

Any ideas why this is needed?

**Comment by mauro-balades** [comment]
Snowball now uses `curl` to fetch packages. I could include `libssl.so.1.1` into the `.snowball/lib` folder

**Comment by mattgodbolt** [comment]
So long as it's compatible with the system we run on, and that snowball is configured to look for it there, that will work.

**Comment by mauro-balades** [comment]
Could you try refreshing the install? I've updated it to contain the libs

**Comment by mattgodbolt** [comment]
will do...one sec...

**Comment by mattgodbolt** [comment]
```
2024-01-15 20:53:52,999 lib.ce_install  INFO     compilers/snowball 0.1.0 installed OK
```

Thank you!!

**Comment by mauro-balades** [comment]
yay! 😄

**Pull request merged**
