### PR TITLE
Adds latest GCC versions for ESP32 target.

### PR DESCRIPTION
**Pull request by euripedesrocha**
Adding the latest release.

### CODE REVIEW

**Comment by partouf** [comment]
You'll still need to add the new compilers to the main repo's configuration https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L1675

**Review by mattgodbolt — APPROVED** [review]
Happy to merge this but these won't appear on the site until we have a PR like the one @partouf mentioned.

**Comment by mattgodbolt** [comment]
I should have tested. sorry @euripedesrocha but these are all 404s:

    self.install_context.fetch_url_and_pipe_to(staging, f"{self.url}", self.tar_cmd, self.untar_to)
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 130, in fetch_url_and_pipe_to
    self.fetch_to(url, fd)
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 105, in fetch_to
    raise FetchFailure(f"Fetch failure for {url}: {request}")
lib.installation_context.FetchFailure: Fetch failure for https://github.com/espressif/crosstool-NG/releases/download/esp-2022r1/xtensa-esp32-elf-gcc11_2_0-esp-2022r1-linux-amd64.tar.gz: <Response [404]>

```
Installing compilers/c++/cross/gcc/xtensa/esp32s2 2022r1
2023-01-11 02:03:18,296 lib.installation_context ERROR    Failed to fetch https://github.com/espressif/crosstool-NG/releases/download/esp-2022r1/xtensa-esp32s2-elf-gcc11_2_0-esp-2022r1-linux-amd64.tar.gz: <Response [404]>
2023-01-11 02:03:18,307 lib.ce_install  INFO     compilers/c++/cross/gcc/xtensa/esp32s2 2022r1 failed to install: Fetch failure for https://github.com/espressif/crosstool-NG/releases/download/esp-2022r1/xtensa-esp32s2-elf-gcc11_2_0-esp-2022r1-linux-amd64.tar.gz: <Response [404]>
Traceback (most recent call last):
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 393, in install
    installable.install()
  File "/home/ubuntu/infra/bin/lib/installable/archives.py", line 195, in install
    self.stage(staging)
  File "/home/ubuntu/infra/bin/lib/installable/archives.py", line 176, in stage
    self.install_context.fetch_url_and_pipe_to(staging, f"{self.url}", self.tar_cmd, self.untar_to)
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 130, in fetch_url_and_pipe_to
    self.fetch_to(url, fd)
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 105, in fetch_to
    raise FetchFailure(f"Fetch failure for {url}: {request}")
lib.installation_context.FetchFailure: Fetch failure for https://github.com/espressif/crosstool-NG/releases/download/esp-2022r1/xtensa-esp32s2-elf-gcc11_2_0-esp-2022r1-linux-amd64.tar.gz: <Response [404]>

Installing compilers/c++/cross/gcc/xtensa/esp32s3 2022r1
2023-01-11 02:03:18,477 lib.installation_context ERROR    Failed to fetch https://github.com/espressif/crosstool-NG/releases/download/esp-2022r1/xtensa-esp32s3-elf-gcc11_2_0-esp-2022r1-linux-amd64.tar.gz: <Response [404]>
2023-01-11 02:03:18,489 lib.ce_install  INFO     compilers/c++/cross/gcc/xtensa/esp32s3 2022r1 failed to install: Fetch failure for https://github.com/espressif/crosstool-NG/releases/download/esp-2022r1/xtensa-esp32s3-elf-gcc11_2_0-esp-2022r1-linux-amd64.tar.gz: <Response [404]>
Traceback (most recent call last):
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 393, in install
    installable.install()
  File "/home/ubuntu/infra/bin/lib/installable/archives.py", line 195, in install
    self.stage(staging)
  File "/home/ubuntu/infra/bin/lib/installable/archives.py", line 176, in stage
    self.install_context.fetch_url_and_pipe_to(staging, f"{self.url}", self.tar_cmd, self.untar_to)
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 130, in fetch_url_and_pipe_to
    self.fetch_to(url, fd)
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 105, in fetch_to
    raise FetchFailure(f"Fetch failure for {url}: {request}")
lib.installation_context.FetchFailure: Fetch failure for https://github.com/espressif/crosstool-NG/releases/download/esp-2022r1/xtensa-esp32s3-elf-gcc11_2_0-esp-2022r1-linux-amd64.tar.gz: <Response [404]>

```

I'm going to revert. We'll be happy to help if you need assistance in reopening the two PRs required.

**Comment by euripedesrocha** [comment]
@mattgodbolt @partouf I will open the configuration MR and will fix the url.

**Comment by mattgodbolt** [comment]
Thanks!

**Pull request merged**
