### PR TITLE
CMake bumped to 3.26.1

### PR DESCRIPTION
**Pull request by bretbrownjr**
Even better C++ modules support WRT #927

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks. Will push live but will need a change to actually use the new cmake (aiui)

**Review by mattgodbolt — APPROVED** [review]

**Comment by mattgodbolt** [comment]
Oh apparently not:
```
2023-03-28 16:20:29,569 lib.installation_context INFO     Symlinking cmake-v3.26.1 to /opt/compiler-explorer/cmake

```

**Comment by partouf** [comment]
works ✔️  https://godbolt.org/z/h8K4oEEe4

**Comment by mattgodbolt** [comment]
Oh, I see:
```
Step cmake returned: 1
-- Configuring incomplete, errors occurred!
CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.26.2 or higher is required.  You are running version 3.26.1
```
:|

**Pull request merged**
