### PR TITLE
Add some more D compilers (dmd releases) to d.yaml

### PR DESCRIPTION
**Pull request by maxhaton**
See what happens.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi! Thanks for updating the available compiler versions. An accompanying PR to the main repo that adds this compilers to `etc/config/d.amazon.properties` will still be needed for the compilers to show up

**Comment by maxhaton** [comment]
@RubenRBS So can you merge it?

**Comment by partouf** [comment]
oh i missed that the compilers aren't added to the main repo
can you do that @maxhaton ?

**Comment by maxhaton** [comment]
> oh i missed that the compilers aren't added to the main repo can you do that @maxhaton ?

If you have a script to do it automatically I'd prefer you did that but if not I'll do it.

**Comment by JohanEngelen** [comment]
@maxhaton  See for an example: https://github.com/compiler-explorer/compiler-explorer/pull/3706

**Pull request merged**
