### PR TITLE
Add Slang

### PR DESCRIPTION
**Pull request by spencer-lunarg**
For https://github.com/compiler-explorer/compiler-explorer/pull/7151

### CODE REVIEW

**Review by AbrilRBS — APPROVED** [review]
Looks good on my side

**Comment by spencer-lunarg** [comment]
@AbrilRBS what is the formatting here, I don't see this python file ... is it because I force pushed a change to remove the extra new line?

image

**Comment by mattgodbolt** [comment]
If you merge main back in it will fix this: sorry for the inconvenience. But in this instance it'll work out if I merge so I'll do that now!

**Comment by mattgodbolt** [comment]
```ce_install install slang
2024-12-02 09:11:01,311 lib.installation_context INFO     Making uncached requests
2024-12-02 09:11:01,312 lib.ce_install  INFO     Creating multiprocessing pool with 2 workers
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 538, in main
    cli(prog_name="ce_install")  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/home/ubuntu/infra/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/infra/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/infra/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/infra/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/infra/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/infra/.venv/lib/python3.10/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 415, in install
    to_do = pool.map(partial(_should_install, force), context.get_installables(filter_))
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 48, in get_installables
    for installer in installers_for(self.installation_context, yaml_doc, self.enabled):
  File "/home/ubuntu/infra/bin/lib/installation.py", line 118, in installers_for
    yield installer_type(install_context, target)
  File "/home/ubuntu/infra/bin/lib/installable/archives.py", line 197, in __init__
    if self.config_get("compression") == "xz":
  File "/home/ubuntu/infra/bin/lib/installable/installable.py", line 218, in config_get
    raise RuntimeError(f"Missing required key '{config_key}' in {self.name}")
RuntimeError: Missing required key 'compression' in compilers/slang/slangc 2024.14.6
```

will fix

**Comment by mattgodbolt** [comment]
Next issue: `RuntimeError: After unpacking, slang-2024.14.6 was not a directory`
...will fix too..

**Comment by mattgodbolt** [comment]
The latest doesn't install either:
```
lib.installation_context.FetchFailure: Fetch failure for https://github.com/shader-slang/slang/releases/download/vlatest/slang-latest-linux-x86_64-glibc-2.17.tar.gz: <Response [404]>
```
will see if I can fix that, else I'll disable it

**Comment by mattgodbolt** [comment]
Merged and installed OK:
```
$ ls -l /opt/compiler-explorer/slang-2024.14.6/
total 32
-rw-r--r-- 1 root root  1490 Nov 26 03:35 LICENSE
-rw-r--r-- 1 root root 11679 Nov 26 03:35 README.md
drwxr-xr-x 2 root root  6144 Nov 26 03:52 bin
drwxr-xr-x 2 root root  6144 Nov 26 03:52 include
drwxr-xr-x 2 root root  6144 Nov 26 03:52 lib
drwxr-xr-x 3 root root  6144 Nov 26 03:52 share
```

**Pull request merged**
