### PR TITLE
[WIP] Build libraries

### PR DESCRIPTION
**Pull request by partouf**
Rebased on master and refactored to be separate py from installation.
Still a bit of a mess, mostly works I think.

**Todo**
- [x] Find a way to not build if source hasn't changed
- [x] Don't let Makefile projects write files to source folder if possible - seems to be harder than it looks, don't think I can make this work
- [x] Find out how to build Catch2
- [x] Delay Conan upload / make a new command
- [x] Option to move build execution logging to files?
- [x] Make webinterface to view current libraries and builds on conanserver
- [x] Noticed I had to kill conanserver when not used for a while, find a fix
- [x] Fix code for the arm compilers with dots in their amazon properties ID
- [x] Secure build Annotation mechanism
- [x] Service startup script for CEConanServer
- [x] ulib 2.4.2 build for "x86-64 clang (old concepts branch)" produces a weird extra x86_64 debug column http://ec2-54-93-113-179.eu-central-1.compute.amazonaws.com:10240/libraries.html - This is because of std++2a being used for clang_concepts, it's fine.

**Terraform things**
- [x] AMI for CEConanServer
- [x] Subdomain and HTTPS cloudfront in front of CEConanServer

### CODE REVIEW

**Comment by partouf** [comment]
Working on a proxy to put in front of Conan-server, since it doesn't offer any way to list the available libraries / versions, and to request every library and version available on CE requires way too much calls.

https://github.com/partouf/conanproxy

REST calls in action:
librarymatrixexample

**Comment by partouf** [comment]
Listed all libraries I have binaries for and am reminded we have libraries installed for ulib and cctz, but aren't actually added to the website...

image

**Comment by partouf** [comment]
Noticed my Free AWS instance had some connectivity issues and wondered if the conanserver hanging was related to that. But I'm pretty sure now it's VSCode probably causing CPU usage to spike due to https://github.com/microsoft/vscode-remote-release/issues/2969
:'(

**Comment by partouf** [comment]
Catch2 v3.0.0-preview2 works like a charm, producing 2 .a files to link against. I think we can forget about building the older versions unless we make a custom CMakeLists.txt and I don't think I'm volunteering for that.

**Comment by partouf** [comment]
Thinking about using the proxy to annotate the builds with gitrevisionhashes, but not sure yet how to store that information, sqlite? I could have another look if Conan doesn't support it somehow, but I think the only way of doing it would be that it be part of the uniquekey, and then we're keeping binaries that have ever lived. But will see.

**Comment by partouf** [comment]
Maybe these v2 calls are the way to go, https://docs.conan.io/en/latest/reference/commands/misc/conan_build_info.html#conan-build-info-v2

Gonna test them out right meow

**Comment by partouf** [comment]
added some calls to the proxy https://github.com/partouf/conanproxy/commit/2c4834b35b39c5cd69b26dad40d2489dc4da902e
to annotate specific builds with a json file, which in this case contains a git commit hash to identify on what git commit the binary was built with - to avoid rebuilding libraries that haven't changed.

It's a bit rough on the edges and not entirely vulnerability free probably, but it works.
So with this - in theory - we could build and upload binaries nightly for trunk versions of libraries.

**Comment by partouf** [comment]
* Terraformed to work conan.compiler-explorer.com (https://conan.compiler-explorer.com/libraries.html)
* Made a packer for an ami for the server

TODO
* [ ] Somehow the ami is 24gb, but it's not supposed to be that big
* [ ] Terraform needs to be refactored to use the existing load balancer instead of a new one
* [ ] I can't upload binaries anymore, the Conan cli returns `ERROR: Wrong user or password.`

**Comment by partouf** [comment]
* Moved into the CE LB and eliminated a lot of config.
* Figured out why login wouldn't work, you have to allow Authorization headers to forward on the Cloudfront end
* Upload still doesn't work, probably something to do with streaming post uploads, had to alter express as well a while back for that, but perhaps cloudfront also needs to be adjusted to allow that.

**Comment by partouf** [comment]
Made the make libraries copy to a staging buildfolder, so in theory we could leave /opt/compiler-explorer now readonly, as already prepared in admin-daily-build.sh

I think the last thing I'm wondering about is how to manage logging. When a build succeeds it's probably not super important until we find a bug somehow, but I do think we probably need to record and perhaps add logging to the build combinations that have failed.

Would be nice to have a matrix HTML page reflecting that as well, but can't add it in the way the libraries matrix page works now (as it fetches things from the conan_server folder, so only things that have been built successfully will be there)

So we'd need something else for that. Maybe I can plug in a sqlite database for it?

**Comment by partouf** [comment]
Seems from benchmark 1.4.0 requires google test to build, so everything fails to build currently for that. I assume it's only for testing the build and is not linked, but the question is with which version it's supposed to run...

The readme mentions just cloning the googletest repo

Will try that first and see where I get stranded

**Comment by partouf** [comment]
Manually did these things, but should probably be added to installer if this actually works:

```
sudo git clone https://github.com/google/googletest.git v1.4.0/googletest
sudo git clone https://github.com/google/googletest.git v1.4.1/googletest
sudo git clone https://github.com/google/googletest.git v1.5.0/googletest
sudo git clone https://github.com/google/googletest.git trunk/googletest
```

**Comment by partouf** [comment]
support for libc++ in clang4.0.0 and 4.0.1 doesn't look great, so I'm gonna disable those too

**Comment by partouf** [comment]
update; bench starting to build now with the cloned googletest folders

**Comment by partouf** [comment]
I'm having the problem that sometimes the builder will stop with this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/build/infra/bin/lib/ce_install.py", line 209, in main
    [num_installed, num_skipped, num_failed] = installable.build(args.buildfor)
TypeError: cannot unpack non-iterable bool object
```

This is about line this exit line (and so it doesn't continue building with other libraries targets):
* https://github.com/compiler-explorer/infra/pull/346/files#diff-cfed323c87baee0b2644e4ab819ebe08R209

But they should trace here, where all I can see is a return value of either these 3 or a RuntimeError throw:
* https://github.com/compiler-explorer/infra/pull/346/files#diff-3779a971eeb7be92f3ff98ba8cac0bdfR352
* https://github.com/compiler-explorer/infra/pull/346/files#diff-441fe92c17144612a932e41caaf259a8R729

I'm not sure how to debug this, as obviously it doesn't always happen, and it's usually not that much of a problem. But this time I was trying to get it to build TBB 2020.3, but it couldn't get past 2020.2 because of that error.

Can someone take a fresh look at this and see what I'm doing wrong?

**Comment by mattgodbolt** [comment]
Per slack, this is I tihnk due to the `return False` on line 698 of library_builder, when the compiler doesn't support a fixed arch

**Comment by partouf** [comment]
Concerning ULibs' missing ulib/internal/config.h
It is generated using `./config.status` or specifically `./config.status --header=include/ulib/internal/config.h`

Considering it contains some very specific compiler and environment info, it's probably best to put this into the binary package.

However, that will mean a lot of reuploading. So I think for now ulib is just not supported until we have reuploaded everything.
I have also seen some extra options to maybe support libc++ and -m32, but not sure about that.

**Comment by partouf** [comment]
Hmm, or maybe just build it as shared...

**Comment by partouf** [comment]
Played around with ULib by adding the config.h to the package. Which seems to work to avoid the include error, and then got rid of some more things by following instructions in https://github.com/compiler-explorer/compiler-explorer/issues/572#issuecomment-336196212 - but leaves an issue of not being able to find some symbols within ulib.a . So I don't know what's next for this.

(and even if it did work, you would still not have the config.h during normal -S mode in CE, which would be confusing for users)

Also didn't seem I could really influence the target architecture or stdlib after all, tried all kinds of parameters for configure.

So it seems this ordeal is near a dead-end.

**Pull request merged**
