### PR TITLE
Update NASM version to 2.16.01

### PR DESCRIPTION
**Pull request by wmentha**
See Issue in compiler-explorer: [#5506](https://github.com/compiler-explorer/compiler-explorer/issues/5506)

See PR in compiler-explorer: [Add NASM 2.16.01](https://github.com/compiler-explorer/compiler-explorer/pull/5528)

Decided to have a go at adding latest NASM release. Let me know if there is anything I missed.

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Looks good: thanks!

**Comment by mattgodbolt** [comment]
There might be a little complication around the machine we (now) install on is on a newer OS than the CE nodes....We'll have to do a bit more work for that if it comes to it.

**Comment by mattgodbolt** [comment]
Darn it: yes, this unfortunately happens:
```
ubuntu@ip-172-30-2-52:~$ /opt/compiler-explorer/nasm-2.16.01/nasm 
/opt/compiler-explorer/nasm-2.16.01/nasm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/compiler-explorer/nasm-2.16.01/nasm)
/opt/compiler-explorer/nasm-2.16.01/nasm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/compiler-explorer/nasm-2.16.01/nasm)
```

so... this unfortunately won't work and it's _not_ your fault. We changed a few things and we're "lucky" the existing nasm builds happen to still work but the correct solution is soethin glike:

- build `nasm` using `misc-builder`
- install from there

Which is someting we can help with. I'm sorry this didn't work out!

**Comment by wmentha** [comment]
@mattgodbolt No worries! Thank you for looking into it. I'll be happy to help out on this if there is anyway I can 😊

**Pull request merged**
