### PR TITLE
Add Solidity 0.8.21

### PR DESCRIPTION
**Pull request by shekhirin**
- https://github.com/ethereum/solidity/releases/tag/v0.8.21
- https://binaries.soliditylang.org/linux-amd64/list.json

### CODE REVIEW

**Comment by partouf** [comment]
Can you add the new version please instead of overriding the previous one? And can you add the new version to https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/solidity.amazon.properties

**Comment by shekhirin** [comment]
> Can you add the new version please instead of overriding the previous one?

I was following the decision in https://github.com/compiler-explorer/infra/commit/4e72256c6dda46c3ac32038d00e2434e8aaa65a3, do we want to add all the versions between `0.8.13` and `0.8.21` too?

**Comment by partouf** [comment]
> > Can you add the new version please instead of overriding the previous one?
> 
> I was following the decision in [4e72256](https://github.com/compiler-explorer/infra/commit/4e72256c6dda46c3ac32038d00e2434e8aaa65a3), do we want to add all the versions between `0.8.13` and `0.8.21` too?

Ah ok, let's keep it like this then

**Review by RubenRBS — APPROVED** [review]
Thanks a lot, we appreciate it :)

Please remember to open a PR in the main repo to update this compiler's version too, thanks!

**Pull request merged**
