### PR TITLE
Remove nuget dependency

### PR DESCRIPTION
**Pull request by hez2010**
We no longer need the additional nuget package. I'm proposing a new way to compile dotnet programs in compiler-explorer.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
I don't think I'm following here. I'm currently still trying to build the 6.* and 7.0.0 with the changes you made but they keep failing to build (did you test them? It was missing cmake, and I'm trying now with that).

Wil this require changes to `compiler-explorer`'s main repo too?

**Comment by hez2010** [comment]
> Wil this require changes to `compiler-explorer`'s main repo too?

Yes. I'm preparing the PR now. Wait a minute :)

**Comment by hez2010** [comment]
Sent https://github.com/compiler-explorer/compiler-explorer/pull/4337

**Comment by mattgodbolt** [comment]
Thanks @hez2010 - hoping to get this sorted :-) appreciate you taking the time to get this done!

**Review by mattgodbolt — APPROVED** [review]

**Pull request merged**
