### PR TITLE
Added ruby 3.2.2 to installs

### PR DESCRIPTION
**Pull request by zenspider**

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Comment by zenspider** [comment]
Is there a ruby 3.3 available somewhere?

**Comment by mattgodbolt** [comment]
oh good point; we build these ourselves it seems: https://github.com/compiler-explorer/ruby-builder so I can build whatever builds that's OK with. I'll do the 3.2.2 one before I merge this (looks like it's missing from our drop-down to easily build from the GH UI)

**Comment by mattgodbolt** [comment]
3.3.0 built too. I'll merge and install both

**Pull request merged**
