### PR TITLE
Enblacken all the files

### PR DESCRIPTION
**Pull request by mattgodbolt**

### CODE REVIEW

**Review by apmorton — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
Reminder to latee add the commit to the `.get-blame-ignore-revs` file

**Comment by partouf** [comment]
does this fix quotes automatically?

**Comment by mattgodbolt** [comment]
All the changes here were 100% automated. I literally added the pre-commit hook and ran it with only the "120c wide" config set.

**Review by partouf — APPROVED** [review]

**Comment by mattgodbolt** [comment]
Thanks all! I'll get any other PRs merged, rebase, rerun and then commit; and then update the blame ignore revs too (thanks @RubenRBS )

**Review by jeremy-rifkin — APPROVED** [review]
looks nice

**Pull request merged**
