### PR TITLE
Add 4.12.0-flambda

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by apmorton** [comment]
hold on merging this please - I am going to convert this installation over to yaml

**Comment by smorimoto** [comment]
I don't have rights to merge this, so give it or please merge this by yourself.

**Comment by apmorton** [comment]
Was mostly leaving a note for other contributors, sorry if that wasn't super clear.
In any case, I am going to close this as the changes in b5747e9dba0959fbbb3e42c1a53d2b2c7d61da96 supersede it.
We are in the process of migrating to a new yaml based compiler installation system and ocaml was somehow left behind.

Thank you for taking the time to add newer ocaml versions!

In the future to add new ocaml versions please edit this file: https://github.com/compiler-explorer/infra/blob/main/bin/yaml/ocaml.yaml

**Comment by smorimoto** [comment]
Oh, thanks for doing that on my behalf!

**Pull request closed without merging**
