### PR TITLE
Add JsonCpp 1.9.4 with CMake

### PR DESCRIPTION
**Pull request by jmarrec**
Add JsonCpp 1.9.4 with CMake (passing arguments to build nothing but the static lib)

cf https://github.com/compiler-explorer/compiler-explorer/issues/2534

### CODE REVIEW

**Comment by partouf** [comment]
Works perfectly, thanks!

**Comment by jmarrec** [comment]
@partouf Thanks for the quick review.

If I can bother you one bit, I what commands are you running locally? 

I am having a few issues and it starts very early with `make ce`, but I thinik it  recovers from it (it says it can build boto3, awscli and wrapt but later does a setup.py install and seems to work

<details>

<summary> make ce output </summary>


```diff
# Deactivate current python venv
$ deactivate
$ make ce
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: boto3, awscli, wrapt
  Building wheel for boto3 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/julien/Software/Others/compiler-explorer/infra/.env/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxm85m8e/boto3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxm85m8e/boto3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-812_8u6h
       cwd: /tmp/pip-install-qxm85m8e/boto3/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for boto3
  Running setup.py clean for boto3
  Building wheel for awscli (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/julien/Software/Others/compiler-explorer/infra/.env/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxm85m8e/awscli/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxm85m8e/awscli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-amx9o295
       cwd: /tmp/pip-install-qxm85m8e/awscli/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for awscli
  Running setup.py clean for awscli
  Building wheel for wrapt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/julien/Software/Others/compiler-explorer/infra/.env/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxm85m8e/wrapt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxm85m8e/wrapt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-nd9_7ivz
       cwd: /tmp/pip-install-qxm85m8e/wrapt/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for wrapt
  Running setup.py clean for wrapt
- Failed to build boto3 awscli wrapt
Installing collected packages: wheel, urllib3, six, python-dateutil, jmespath, botocore, s3transfer, boto3, pyyaml, colorama, docutils, pyasn1, rsa, awscli, chardet, idna, certifi, requests, msgpack, lockfile, cachecontrol, py, pluggy, pyparsing, packaging, attrs, toml, iniconfig, pytest, typed-ast, mypy-extensions, typing-extensions, mypy, isort, mccabe, wrapt, lazy-object-proxy, astroid, pylint, MarkupSafe, jinja2
    Running setup.py install for boto3 ... done
    Running setup.py install for awscli ... done
    Running setup.py install for wrapt ... done
Successfully installed MarkupSafe-1.1.1 astroid-2.5.2 attrs-20.3.0 awscli-1.19.40 boto3-1.17.40 botocore-1.20.40 cachecontrol-0.12.6 certifi-2020.12.5 chardet-4.0.0 colorama-0.4.3 docutils-0.15.2 idna-2.10 iniconfig-1.1.1 isort-5.8.0 jinja2-2.11.3 jmespath-0.10.0 lazy-object-proxy-1.6.0 lockfile-0.12.2 mccabe-0.6.1 msgpack-1.0.2 mypy-0.812 mypy-extensions-0.4.3 packaging-20.9 pluggy-0.13.1 py-1.10.0 pyasn1-0.4.8 pylint-2.7.3 pyparsing-2.4.7 pytest-6.2.2 python-dateutil-2.8.1 pyyaml-5.4.1 requests-2.25.1 rsa-4.7.2 s3transfer-0.3.6 six-1.15.0 toml-0.10.2 typed-ast-1.4.2 typing-extensions-3.7.4.3 urllib3-1.26.4 wheel-0.36.2 wrapt-1.12.1
```
</details>


So moving on, this works:

```
./bin/ce_install install libraries/c++/jsoncpp 1.9.4
2021-03-29 23:28:42,611 lib.installation INFO     Making uncached requests
Installing libraries/c++/jsoncpp 1.9.4
2021-03-29 23:28:44,287 lib.installation INFO     Fetching https://github.com/open-source-parsers/jsoncpp/archive/1.9.4.tar.gz (0 bytes)
2021-03-29 23:28:44,370 lib.installation INFO     100% of https://github.com/open-source-parsers/jsoncpp/archive/1.9.4.tar.gz
2021-03-29 23:28:44,370 lib.installation INFO     Piping to tar zxf -
2021-03-29 23:28:44,385 lib.installation INFO     Moving from staging (/opt/compiler-explorer/staging/jsoncpp-1.9.4) to final destination (/opt/compiler-explorer/libs/jsoncpp/1.9.4)
2021-03-29 23:28:44,387 lib.installation INFO     libraries/c++/jsoncpp 1.9.4 installed OK
1 packages installed OK, 0 skipped, and 0 failed installation
```

Then I can't figure out how to actually build it?
I thought I'd try to install one of the compilers. That works too

```
$ ./bin/ce_install install compilers/c++/x86/gcc 9.3.0
2021-03-29 23:31:27,552 lib.installation INFO     Making uncached requests
Installing compilers/c++/x86/gcc 9.3.0
2021-03-29 23:31:29,011 lib.installation INFO     Fetching https://s3.amazonaws.com/compiler-explorer/opt/gcc-9.3.0.tar.xz (148866460 bytes)
2021-03-29 23:31:37,313 lib.installation INFO     2.8% of https://s3.amazonaws.com/compiler-explorer/opt/gcc-9.3.0.tar.xz...
2021-03-29 23:31:42,335 lib.installation INFO     16.9% of https://s3.amazonaws.com/compiler-explorer/opt/gcc-9.3.0.tar.xz...
2021-03-29 23:31:47,337 lib.installation INFO     67.6% of https://s3.amazonaws.com/compiler-explorer/opt/gcc-9.3.0.tar.xz...
2021-03-29 23:31:49,099 lib.installation INFO     100% of https://s3.amazonaws.com/compiler-explorer/opt/gcc-9.3.0.tar.xz
2021-03-29 23:31:49,102 lib.installation INFO     Piping to tar Jxf -
2021-03-29 23:31:58,546 lib.installation INFO     Moving from staging (/opt/compiler-explorer/staging/gcc-9.3.0) to final destination (/opt/compiler-explorer/gcc-9.3.0)
2021-03-29 23:31:58,547 lib.installation INFO     Destination /opt/compiler-explorer/gcc-9.3.0 exists, temporarily moving out of the way (to /opt/compiler-explorer/staging/temp_orig)
2021-03-29 23:31:58,549 lib.installation INFO     compilers/c++/x86/gcc 9.3.0 installed OK
1 packages installed OK, 0 skipped, and 0 failed installation

```

Trying to build is a failure though:

```
$ ./bin/ce_install build libraries/c++/jsoncpp
2021-03-29 23:32:52,083 lib.installation INFO     Making uncached requests
Building libraries/c++/jsoncpp 1.9.4 for all
2021-03-29 23:32:53,457 lib.installation ERROR    Unknown compiler 
2021-03-29 23:32:53,477 lib.installation INFO     Building jsoncpp for [g93,,/opt/compiler-explorer/gcc-9.3.0,Linux,Debug,x86_64,,,]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/julien/Software/Others/compiler-explorer/infra/bin/lib/ce_install.py", line 226, in main
    [num_installed, num_skipped, num_failed] = installable.build(args.buildfor)
  File "/home/julien/Software/Others/compiler-explorer/infra/bin/lib/installation.py", line 414, in build
    return builder.makebuild(buildfor)
  File "/home/julien/Software/Others/compiler-explorer/infra/bin/lib/library_builder.py", line 799, in makebuild
    buildstatus = self.makebuildfor(compiler, options, exe, compilerType, toolchain, buildos, buildtype, arch, stdver, stdlib, flagscombination, self.compilerprops[compiler]['ldPath'])
  File "/home/julien/Software/Others/compiler-explorer/infra/bin/lib/library_builder.py", line 652, in makebuildfor
    if self.is_already_uploaded(buildfolder):
  File "/home/julien/Software/Others/compiler-explorer/infra/bin/lib/library_builder.py", line 578, in is_already_uploaded
    annotations = self.get_build_annotations(buildfolder)
  File "/home/julien/Software/Others/compiler-explorer/infra/bin/lib/library_builder.py", line 538, in get_build_annotations
    conanhash = self.get_conan_hash(buildfolder)
  File "/home/julien/Software/Others/compiler-explorer/infra/bin/lib/library_builder.py", line 483, in get_conan_hash
    conaninfo = subprocess.check_output(['conan', 'info', '-r', 'ceserver', '.'] + self.current_buildparameters, cwd=buildfolder).decode('utf-8', 'ignore')
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conan'
```

What am I missing?

**Comment by partouf** [comment]
The best way to invoke a test build in this case is:
`bin/ce_install --buildfor g92 --dry_run build jsoncpp`

Leaving out the `--dry_run` will try to query and use our conanserver (and we have a non-default configuration to query our conan server - and we use some custom api's)

**Comment by jmarrec** [comment]
Thanks a bunch!

**Pull request merged**
