### PR TITLE
bin: libraries: add liblzma (v5.6.2)

### PR DESCRIPTION
**Pull request by thesamesam**

### CODE REVIEW

**Comment by thesamesam** [comment]
I've tested https://github.com/compiler-explorer/compiler-explorer/pull/6542 but not yet managed to test this side as it fails to compile `cffi`. I'll try a bit harder.

**Comment by mattgodbolt** [comment]
I'm not quite sure what packer has to do here with anything...I will merge and we'll see what happens.

**Review by mattgodbolt — APPROVED** [review]

**Comment by mattgodbolt** [comment]
That'll teach me:

```
 [404]>
2024-06-08 01:41:31,926 lib.ce_install  INFO     libraries/c++/liblzma 5.6.2 failed to install: Fetch failure for https://github.com/tukaani/xz/archive/v5.6.2.tar.gz: <Response [404]>
Traceback (most recent call last):
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 421, in install
    installable.install()
  File "/home/ubuntu/infra/bin/lib/installable/git.py", line 213, in install
    self.stage(staging)
  File "/home/ubuntu/infra/bin/lib/installable/git.py", line 187, in stage
    self.install_context.fetch_url_and_pipe_to(staging, self.get_archive_url(), self.get_archive_pipecommand())
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 148, in fetch_url_and_pipe_to
    self.fetch_to(url, fd, agent)
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 123, in fetch_to
    raise FetchFailure(f"Fetch failure for {url}: {request}")
lib.installation_context.FetchFailure: Fetch failure for https://github.com/tukaani/xz/archive/v5.6.2.tar.gz: <Response [404]>

0 packages installed OK, 0 skipped, and 1 failed installation
Failed:
  libraries/c++/liblzma 5.6.2
```

I'll fix this.

**Comment by mattgodbolt** [comment]
> I'll fix this.

I can't unfortantely: https://github.com/tukaani/xz this isn't a valid github repo. I'm going to revert this change; please let me know if I can help you with this.

**Comment by thesamesam** [comment]
I'll fix it up later today, sorry. packer is used by the Makefile to test unless I misread the docs?

**Comment by thesamesam** [comment]
Fixed PR at https://github.com/compiler-explorer/infra/pull/1322, sorry again.

**Pull request merged**
