### PR TITLE
Add OpenJDK 19 & 20

### PR DESCRIPTION
**Pull request by Goooler**
https://jdk.java.net/19
https://jdk.java.net/20

### CODE REVIEW

**Comment by Goooler** [comment]
For https://github.com/compiler-explorer/compiler-explorer/pull/4952.

**Comment by mattgodbolt** [comment]
Thanks

**Comment by mattgodbolt** [comment]
Installation failed:
```
2023-04-10 13:00:35,566 lib.ce_install  INFO     compilers/java 19.0.2 failed to install: After unpacking, jdk-19 was not a directory
Traceback (most recent call last):
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 393, in install
    installable.install()
  File "/home/ubuntu/infra/bin/lib/installable/archives.py", line 195, in install
    self.stage(staging)
  File "/home/ubuntu/infra/bin/lib/installable/archives.py", line 182, in stage
    raise RuntimeError(f"After unpacking, {self.untar_path} was not a directory")
RuntimeError: After unpacking, jdk-19 was not a directory

```

java 20 was ok.

**Comment by mattgodbolt** [comment]
The directory is apparently
```
drwxr-xr-x 8 root root 6144 Apr 10 13:01 jdk-19.0.2
```

**Comment by mattgodbolt** [comment]
The directory is apparently
```
drwxr-xr-x 8 root root 6144 Apr 10 13:01 jdk-19.0.2
```

**Comment by mattgodbolt** [comment]
The directory is apparently
```
drwxr-xr-x 8 root root 6144 Apr 10 13:01 jdk-19.0.2
```

**Comment by mattgodbolt** [comment]
Fixed up

**Pull request merged**
