### PR TITLE
Add Python 3.12

### PR DESCRIPTION
**Pull request by narpfel**
Related PR in compiler-explorer: https://github.com/compiler-explorer/compiler-explorer/pull/5968

### CODE REVIEW

**Comment by mattgodbolt** [comment]
@narpfel we'll take whichever versions you think are useful. Usually the more the merrier, disk space is (sort of) cheap :)

**Review by mattgodbolt — APPROVED** [review]
Thanks

**Comment by narpfel** [comment]
> @narpfel we'll take whichever versions you think are useful. Usually the more the merrier, disk space is (sort of) cheap :)

I meant updating the existing Python versions to their latest bugfix releases (e. g. Python3.11 on CE is 3.11.0, but the current version is 3.11.7).

More than one of each minor is probably overkill as there usually should not be any differences apart from bugfixes.

**Comment by mattgodbolt** [comment]
We like to keep all previously-installed versions where possible as that makes it easier for both:
- link stability - if someone has shortlinked something v1.2.3 they might be surprised when it becomes v1.2.5
- bug reporting/checking - if someone files a bug against v1.2.3 it's nice to see a reproducible case and then also show that it has been fixed. if we replace 1.2.3 with 1.2.5 it breaks that
We do make exceptions to this, but right now I'd say if you were so minded; PR _adding_ the most recent point release for each. We can install those and configure them, leaving the previous versions there.

**Pull request merged**
