### PR TITLE
Add libassert

### PR DESCRIPTION
**Pull request by jeremy-rifkin**

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
I haven't been able to test this fully locally yet, I run into issues with conan when I run `./bin/ce_install build libassert`

**Comment by partouf** [comment]
make sure you mkdir -p /opt/compiler-explorer/staging
you can use `bin/ce_install --dry_run --buildfor g121 build libassert`
use --debug in the middle for some more extra stuff
and it will mention in which folder the builds have been put into, you can see whats going right/wrong there

**Comment by partouf** [comment]
it's created a libassert.a for me, so not shared like you set as lib_type

**Comment by jeremy-rifkin** [comment]
Thank you @partouf!

**Pull request merged**
