### PR TITLE
Update to cmake 3.28.0

### PR DESCRIPTION
**Pull request by mattgodbolt**

### CODE REVIEW

**Comment by joblobob** [comment]
Yeah I was excited also :-D but the real 3.28 might be around the corner soon :-P

**Comment by joblobob** [comment]
it is here!!! 🥳 
https://www.kitware.com/cmake-3-27-8-available-for-download/

**Comment by partouf** [comment]
3.27.8 is now available, but 3.28 not yet

**Comment by joblobob** [comment]
> 3.27.8 is now available, but 3.28 not yet

**whistles** oh yeah, I haven't made that error did I? :-D

**Pull request merged**
