### PR TITLE
Update dotnet versions

### PR DESCRIPTION
**Pull request by hez2010**
Also cleanup versions that will not be used after update on the main site

### CODE REVIEW

**Comment by mattgodbolt** [comment]
v6.0.36 doesn't build: https://github.com/compiler-explorer/infra/actions/runs/12015798773/job/33494624984
```
2024-11-25T18:00:05.0382408Z Time Elapsed 00:00:05.20
2024-11-25T18:00:05.0532764Z + ./.dotnet/dotnet tool install --tool-path /root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/dotnet-tools ilspycmd --prerelease --add-source https://api.nuget.org/v3/index.json
2024-11-25T18:00:06.4717983Z /tmp/d8129532-63b5-4a8b-a734-62c0c83eeb36/restore.csproj : error NU1202: Package ilspycmd 9.0.0.7833-preview3 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / any. Package ilspycmd 9.0.0.7833-preview3 supports: net8.0 (.NETCoreApp,Version=v8.0) / any
2024-11-25T18:00:06.5168666Z The tool package could not be restored.
2024-11-25T18:00:06.5169293Z Tool 'ilspycmd' failed to install. This failure may have been caused by:
2024-11-25T18:00:06.5169676Z 
2024-11-25T18:00:06.5170052Z * You are attempting to install a preview release and did not use the --version option to specify the version.
2024-11-25T18:00:06.5170729Z * A package by this name was found, but it was not a .NET tool.
2024-11-25T18:00:06.5171344Z * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
2024-11-25T18:00:06.5171897Z * You mistyped the name of the tool.
2024-11-25T18:00:06.5172107Z 
2024-11-25T18:00:06.5172487Z For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
2024-11-25T18:00:15.0633812Z ##[error]Process completed with exit code 1.
2024-11-25T18:00:15.0729031Z Post job cleanup.
2024-11-25T18:00:15.1656292Z [command]/usr/bin/git version
```

seems related to https://github.com/compiler-explorer/dotnet-builder/pull/20

**Comment by hez2010** [comment]
Sorry, I forgot that ilspycmd doesn't support .NET 6.0 and .NET 7.0 anymore. We should filter out versions less than .NET 8.0 in the build script.

**Comment by hez2010** [comment]
I submit a fix for that, please take a look.

**Comment by mattgodbolt** [comment]
Thanks: I'll rebduilt 7.0.20 and 6.0.36 once that lands and test

**Comment by mattgodbolt** [comment]
All rebuilt: thanks.

**Review by mattgodbolt — APPROVED** [review]

**Pull request merged**
