### PR TITLE
Add HPC SDK 23.9 to cpp.yaml

### PR DESCRIPTION
**Pull request by jmuddnv**

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks

**Comment by mattgodbolt** [comment]
Installing now...

**Comment by mattgodbolt** [comment]
Took 24m but now installed.

**Comment by jmuddnv** [comment]
Let me know if that's something on the way I did the PR -- since it was my first time doing that -- or whether you think it was due to something unrelated.

**Comment by mattgodbolt** [comment]
No it's just how long it takes, no worries! :) sorry inconsequential stuff

**Comment by jmuddnv** [comment]
@mattgodbolt HPC SDK 23.9 doesn't seem to be showing up on godbolt.org.  Any ideas?
image

**Comment by partouf** [comment]
I'm refreshing the instances at the moment, it should appear soon.
Thanks for letting us know, we forgot some steps after merging this.

**Pull request merged**
