### PR TITLE
Add cross GCC 12.2 for several targets

### PR DESCRIPTION
**Pull request by dkm**
refs https://github.com/compiler-explorer/compiler-explorer/issues/3973

Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

### CODE REVIEW

**Comment by dkm** [comment]
Depends on : https://github.com/compiler-explorer/gcc-cross-builder/pull/34

**Comment by dkm** [comment]
gcc-cross-compiler merged. Listing build/install status here:

* arm:
  * [ ] build in infra
  * [ ] install
* arm64:
  * [ ] build in infra
  * [ ] install
* avr:
  * [ ] build in infra
  * [ ] install
* mips:
  * [ ] build in infra
  * [ ] install
* mips64:
  * [ ] build in infra
  * [ ] install
* mips64el:
  * [ ] build in infra
  * [ ] install
* mipsel:
  * [ ] build in infra
  * [ ] install
* msp430:
  * [ ] build in infra
  * [ ] install
* powerpc:
  * [ ] build in infra
  * [ ] install
* powerpc64:
  * [ ] build in infra
  * [ ] install
* powerpc64le:
  * [ ] build in infra
  * [ ] install
* riscv32:
  * [ ] build in infra
  * [ ] install
* riscv64:
  * [ ] build in infra
  * [ ] install
* s390x:
  * [ ] build in infra
  * [ ] install

**Comment by dkm** [comment]
This is ready :). Compilers installed using the following command:
```
$ for i in arm avr mips powerpc s390x riscv32 riscv64; do 
  ./bin/ce_install install $i 12.2.0
done      
$ ./bin/ce_install install compilers/c/cross/gcc/msp430 12.2.0
```

There should be 14 compilers installed (13 with first command, 1 with last one).

**Comment by partouf** [comment]
15 compilers installed (install cmd was missing arm64)

**Comment by dkm** [comment]
Strange, the "arm" should match also arm64 (as does "mips" for 3 mips and powerpc for all ppc)

**Comment by dkm** [comment]
And there are only 14 compilers:
- arm
- arm64
- mips
- mips64
- mipsel
- mips64el
- ppc
- ppc64
- ppc64le
- s390x
- rv32
- rv64
- msp430
- avr
So that's even weirder. Am I missing one in the list?

**Comment by partouf** [comment]
I probably got confused with the x86 gcc

**Pull request merged**
