### PR TITLE
Added p2998

### PR DESCRIPTION
**Pull request by Bekenn**
See:

* https://github.com/compiler-explorer/clang-builder/pull/77
* https://github.com/compiler-explorer/compiler-workflows/pull/30

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Installed OK (and will install nightly from now on automatically)

**Comment by Bekenn** [comment]
I appreciate all the help!

**Comment by mattgodbolt** [comment]
sorry it's taking a while to merge in these; I'm doing it in between something else :D Should be all set and merged and then released tomorrow morning GMT though

**Comment by Bekenn** [comment]
No worries!  I'm just incredibly grateful the site exists at all; being able to use it as a test bed for prospective standards work is downright amazing.

**Pull request merged**
