### PR TITLE
[MS] Readme changes

### PR DESCRIPTION
**Pull request by partouf**
I kept forgetting about this, so here a draft PR with the todo list that I have to work on

### TODO
* [x] Add to Readme where-to-download the latest PS
* [x] Add to Readme hint on how to link up a VS (_For example if you have your MSVC installed at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610
Copy 14.25.28610 to your datadirectory E:\MsvceData\msvc_)
* [x] Add to Readme that adding `-Verbose` to commands increases logging
* [x] Add to Readme existence of `Get-MsvceToolsetVersions` and `Get-MsvceVcpkgLibraryList` for info about configured toolsets and libraries
* [x] Add to Readme about doing `Import-Module -Force .\Msvce.psm1` when you've made changes to the PS file
* [x] Add to Readme examples like
  - To check if a MSVC version is installed: `Test-MsvceToolsetExistence -DataDirectory c:\msvcedata -Version 1.2.1234`
  - To check MSVC toolsets after libraries have already been installed: `Build-MsvceDataDirectory -DataDirectory E:\MsvceData -DockerTag 20190905 -SkipVcpkgLibraries -SkipVcpkgBootstrap`

### CODE REVIEW

**Comment by partouf** [comment]
I had some other things in a notepad on my pc:

> To check what libraries are in the json file:
> Test-MsvceToolsetExistence
> 
> To check the MSVC versions that are in the json file:
> Get-MsvceToolsetVersions
> 
> To check if a MSVC version is installed:
> Test-MsvceToolsetExistence -DataDirectory x -Version 1.2.1234
> 
> Testing the script requires Import-Module -Force .\Msvce.psm1 after changes have been made.
> 
> Enabling verbose logging: add -Verbose to the command
> 
> 
> Params for Build-MsvceDataDirectory
> * -DataDirectory
> * -DockerTag
> * -SkipVerifyToolsets
> * -CleanVcpkgDirectory
> * -SkipVcpkgLibraries
> * -SkipVcpkgBootstrap
> * -Clean
> 
> So for example to check MSVC toolsets after libraries have already been installed:
> Build-MsvceDataDirectory -DataDirectory E:\MsvceData -DockerTag 20190905 -SkipVcpkgLibraries -SkipVcpkgBootstrap
> 
> 
> How to use a MSVC installation Copy your MSVC installation from the version number folder to your datadirectory\msvc.
> For example if you have your MSVC installed at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610
> Copy 14.25.28610 to your datadirectory E:\MsvceData\msvc
> 
> For demangling data/msvc/1/bin/Hostx64/x64/undname.exe is used, so duplicate your latest version also to match that folder?
>

**Comment by partouf** [comment]
Found a little bug, don't think it's serious, but will need to debug.

```
PS D:\git\infra\windows\vcpkg> Build-MsvceDataDirectory -DataDirectory E:\Msvcedata -DockerTag 20210101

WARNING: Msvc toolset not present in msvce-config.json is found at: E:\Msvcedata\msvc\E:\Msvcedata\msvc\14.27.29111
WARNING: Msvc toolset 14.14.26428.1 present in msvce-config.json is missing from DataDirectory: E:\Msvcedata
WARNING: Msvc toolset 14.15.26726 present in msvce-config.json is missing from DataDirectory: E:\Msvcedata
```

The first line here is the problem where 2 paths are concatenated to each other for some reason while the others are not.

**Comment by partouf** [comment]
Turns out the demangler issue only occurred when you only had 1 compiler

**Comment by partouf** [comment]
Also fixed the verification warning

**Review by strega-nil — APPROVED** [review]

**Pull request merged**
