### PR TITLE
add newer dotnet versions

### PR DESCRIPTION
**Pull request by kasperk81**
8.0 and minor versions of 6 & 7

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks

**Comment by mattgodbolt** [comment]
Building now:
- https://github.com/compiler-explorer/infra/actions/runs/6963711141
- https://github.com/compiler-explorer/infra/actions/runs/6963712242
- https://github.com/compiler-explorer/infra/actions/runs/6963714431

**Comment by mattgodbolt** [comment]
7.0.14 Failed to build: https://github.com/compiler-explorer/infra/actions/runs/6963712242/job/18949761185
```
  MSBuild version 17.4.8+6918b863a for .NET
    Determining projects to restore...
  /tmp/app/app.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.App.Runtime.linux-x64. No packages exist with this id in source(s): /root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/aot
  /tmp/app/app.csproj : error NU1102: Unable to find package runtime.linux-x64.Microsoft.DotNet.ILCompiler with version (= 7.0.12)
  /tmp/app/app.csproj : error NU1102:   - Found 1 version(s) in /root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/aot [ Nearest version: 7.0.14 ]```
  
  I have no idea how to fix that, unfortauntely

**Comment by mattgodbolt** [comment]
v8.0.0 failed too. Only v6.0.25 built OK. I filed a bug in the dotnet repo: any help you can offer is appreciated.

**Comment by hez2010** [comment]
> I have no idea how to fix that, unfortauntely

A workaround is to disable AOT build, i.e. setting `AOT_BUILD_NEEDED=0`.

**Comment by partouf** [comment]
I'm assuming this is about the template app that's used? Then it should download the runtime packages during this buildscript, yes. And after publish and downloading, it should probably be removed again so it won't be tempted to access the internet from the compiler instances.

**Pull request merged**
