### PR TITLE
Add NSIMD library

### PR DESCRIPTION
**Pull request by JDPailleux**
Following our exchanges, here are the modifications made for the installation of NSIMD.

### CODE REVIEW

**Comment by apmorton** [comment]
I have taken the changes proposed here and adapted them to run in our misc-builder docker image: https://github.com/compiler-explorer/misc-builder/commit/879c56f69fe9279b2af63735b92e46a588b4372a

This lets us build once and produce a tarball that we can install repeatedly, and keeps things off our underpowered admin node.

The build works in our docker setup now, and I can produce a tarball and update the installer yaml whenever we are ready to go.

My only question at this point is what is the versioning expectation?
We are building from the spmd branch - and you have no recent tags.

- Is this a one-and-done?
- Is this spmd branch a rolling target that is going to be updated on your side continuously?
- If so, do you expect us to rebuild on an ongoing basis to keep this up to date?

If you are going to do more conventional releases it would be convenient for us if you could tag them in git so we can build based on tags instead of branches.

**Comment by gquintin** [comment]
Hi @apmorton,

In fact we would like to adapt to compiler-explorer way of doing things for "trunk". For now we have a v1. The spmd branch will be v2. It takes time because we are waiting our CI for testing before merging into master and tagging a v2. We have faced hardware problems which took (too much) time.

Is it more convenient for you if we make a new branch which is called trunk?
Do you pull every night or something from trunk to have an up-to-date library?

So when we will have our CI, I would say a v2 (which is fixed) and trunk. But is it how you desgined CE to work?

**Comment by apmorton** [comment]
Do you have a sense of how long it will be before you are ready to tag v2.0 on your end? If we are only a short time away from that maybe we can wait until then and build/publish v2.0 as a fixed release on CE.

Once we have a fixed release on CE we can think about doing a nightly build of your trunk. Most of our library trunk versions are header only, so the effort on our end is minimal - we just `git pull` every night. We do have some libraries being built nightly, but the process is relatively new.

**Comment by gquintin** [comment]
Hi @apmorton I just got some news from my sysadmin, our CI is almost ready, I have to begin testing it right now. we still have some issues with somes Ubuntu hosts but I am confident they will be resolved by the end of this week. So if were to give you a date, I would say in two weeks --> 23 october. By then I will have released v2. Is it OK with you?

**Comment by apmorton** [comment]
👍 
Sounds good to me - just ping here when v2 is tagged in your repo and I will kick off a build and publish to the site.

**Comment by partouf** [comment]
@gquintin @JDPailleux I think there was out-of-your-control things going on - on this, but if you have any updates, please do share the current status of things

**Comment by gquintin** [comment]
Hi @partouf. Indeed we had problems with our harware and our CI. These problems are now (at least it seems so) resolved. I have ran the tests and I have released v2. I will tag it during this WE and @JDPailleux will continue his work concerning CE on monday.

**Comment by apmorton** [comment]
Hi,

These changes have been integrated into the build script in our misc-builder docker image, so this PR doesn't need to be merged.

In the future if you need to change any build settings please make a PR to the misc-builder repo modifying this file: https://github.com/compiler-explorer/misc-builder/blob/main/build/build-nsimd.sh

If you need to add a new version without modifying any build settings, you can open a PR here which simply adds the new version tag here (and corresponding PR in the main CE repo to add the new version to the property files): https://github.com/compiler-explorer/infra/blob/fa461925498bbb6b3d48f33bd7d0e388b9098c17/bin/yaml/libraries.yaml#L233-L234

When we merge the PR we will manually kick off the build of the new version.

**Pull request closed without merging**
