### PR TITLE
Add more recent OCaml versions

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Thank you for providing OCaml support, I use it regularly.

I added newer OCaml versions based on the diff of https://github.com/compiler-explorer/infra/pull/758 but I don't understand how the infrastructure is setup to install those. So I doubt this works as is. 

What extra changes are required to setup those OCaml versions?

### CODE REVIEW

**Comment by partouf** [comment]
Compilers that need building:
- [ ] 4.14.2
- [ ] 4.14.2-flambda
- [ ] 5.1.0
- [ ] 5.1.1
- [ ] 5.2.0

**Comment by partouf** [comment]
hi @tmcgilchrist you'll also need to send a PR to the main repo, something similar to https://github.com/compiler-explorer/compiler-explorer/pull/4464/files

**Comment by mattgodbolt** [comment]
I'll work on the PR to add them and link them here. They installed OK locally.

**Comment by mattgodbolt** [comment]
These are now live

**Comment by tmcgilchrist** [comment]
Thank you very much. 

My apologies, making this change fell off my todo list.

**Pull request merged**
