### PR TITLE
Update vectorclass library 2

### PR DESCRIPTION
**Pull request by dokempf**
This is the second attempt to update the VCL to 2.01.03. I am sorry for the earlier mistake in PR #430 , I got confused by the slight inconsistencies in tagging and naming of releases upstream: https://github.com/vectorclass/version2/releases

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Got it no problems.

**Comment by mattgodbolt** [comment]
To actually see it on the site we'll need a change to the compiler-explorer repo to, bringing it in.

**Comment by dokempf** [comment]
Will submit that PR, thanks.

**Comment by mattgodbolt** [comment]
Thank _you_! :)

**Pull request merged**
