### PR TITLE
Add clang13.0.1

### PR DESCRIPTION
**Pull request by mattgodbolt**

### CODE REVIEW

**Review by matsjla — COMMENTED** [review]
Missing entry in libraries.yaml

**Comment by mattgodbolt** [comment]
> Missing entry in libraries.yaml

I haven't built the clang libraries for this release.

**Comment by mattgodbolt** [comment]
I guess I will though :D

**Comment by mattgodbolt** [comment]
https://github.com/compiler-explorer/compiler-workflows/actions/runs/1802964494 running now :)

**Comment by mattgodbolt** [comment]
Done! :) Thanks for pinging me about this, I was being lazy!

**Review by matsjla — APPROVED** [review]
LGTM

**Pull request merged**
