### PR TITLE
Add NVTX CUDA library

### PR DESCRIPTION
**Pull request by jrhemstad**
Adds configurations for the 3.0.1 and `dev` branch of [NVTX ](https://github.com/NVIDIA/NVTX)

### CODE REVIEW

**Comment by jrhemstad** [comment]
@mattgodbolt Not sure why CI is failing. The error message looks unrelated to this PR.

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Comment by mattgodbolt** [comment]
Getting:

```
2020-10-19 20:56:20,605 lib.installation INFO     libraries/cuda/nightly/nvtx dev installed OK
Installing libraries/cuda/nvtx 3.0.1
error: pathspec '3.0.1' did not match any file(s) known to git
```

-- any clues before I dig, @jrhemstad ? Were you able to test this locally first? (If not, it _should_ be easy to do: `ce_install` should Just Work™ if you run e.g. `bin/ce_install install libraries nvtx --enable nightly` )

**Comment by mattgodbolt** [comment]
Oh I spotted it, `v` prefix needed. Will fix!

**Pull request merged**
