### PR TITLE
Add LDC 1.28.0

### PR DESCRIPTION
**Pull request by JohanEngelen**

### CODE REVIEW

**Comment by JohanEngelen** [comment]
please wait with merging this

**Review by mattgodbolt — APPROVED** [review]

**Comment by mattgodbolt** [comment]
Thank you!

**Comment by mattgodbolt** [comment]
Oh doops! I'm so sorry I merged and of course it's not working (oops)

**Comment by mattgodbolt** [comment]
I am going to revert this and the other change. Sorry!

**Comment by JohanEngelen** [comment]
@mattgodbolt In case you were wondering: I wanted to wait with this because I knew the `.1` release would happen soon, so as not to clutter CE with multiple `1.28.x` LDC versions. Fixed in the new PR I just submitted :)

**Pull request merged**
