### PR TITLE
[clang] Add Pattern Matching C++ Prototype

### PR DESCRIPTION
**Pull request by lenary**
This is dependent on https://github.com/compiler-explorer/clang-builder/pull/17

This enables https://github.com/compiler-explorer/infra/issues/281

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Looks good: Thanks!

**Comment by mattgodbolt** [comment]
This will take a while to propagate, but I'll babysit it for now and test it once it's built and post back here when so.

**Comment by mattgodbolt** [comment]
```
$ /opt/compiler-explorer/clang-patmat-trunk/bin/clang --version
clang version 10.0.0 (https://github.com/dansarginson/llvm-project.git 18f6789e70a805bca4f0c734fc83143b8b712d9c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-patmat-trunk/bin
```
yay

**Comment by lenary** [comment]
@mattgodbolt thanks for approving these - I may need to change the branch that gets pulled by the builder, but that shouldn't affect the configuration here or the bit I propose for compiler-explorer itself.

**Comment by mattgodbolt** [comment]
Sure thing: just let me know :)

**Pull request merged**
