### PR TITLE
Add Dart v2.19 and v3.0

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by RubenRBS** [comment]
Thanks a lot. I hope they didnt change much between v2 and v3 :)

**Comment by kevmoo** [comment]
The output for this got a LOT better!

```dart
// Type your code here, or load an example.
int square(int num) {
  return num * num;
}

int main(List<String> args) {
    return square(67);
}
```

**Comment by RubenRBS** [comment]
I meant the build side of things, Im just now checking out the differences for the code itself and yeah! Looking nice!

**Comment by kevmoo** [comment]
On the build side we should be SUPER stable.

**Pull request merged**
