### PR TITLE
[clang] Build Patch Versions

### PR DESCRIPTION
**Pull request by lenary**
This adds all the versions listed on `releases.llvm.org`.

I'm not sure if I need to edit anywhere else to support these, and I want to look at ensuring I can build them before proposing this as a real PR.

### CODE REVIEW

**Comment by lenary** [comment]
The dockerized `clang-builder` copes with invoking with these version numbers.

I'm still building the compilers, but if i can get them all loaded into my CE container, I'll add configurations for these compilers.

Unfortunately, I'll probably need one of you to build the real editions of all these clang versions, and push them to s3.

**Comment by partouf** [comment]
We usually build these manually using clang-builder. Can't do it right now, but will see if I can build em in the morning.

**Comment by lenary** [comment]
I guessed it was something along those lines, I'm not sure how urgent this is, as it seems it's something I need your help with more than updating the config to add clang support :)

**Comment by partouf** [comment]
I just built 9.0.1 and 8.0.1, so you should be able to install them with this script if you want. I haven't checked if they're actually correct.

**Comment by lenary** [comment]
Cool, the builds I did with the `clang-builder` look to be working (I'm just downloading the versions you built now), so I'll start a PR to add them to the main configuration in the main repo, which feels like the next step?

**Comment by lenary** [comment]
@partouf shall I start with 8.0.1 and 9.0.1, or should I wait longer for you to finish more? I'm fine either way.

**Comment by partouf** [comment]
ah, right, super sorry, will build the remaining versions as soon as my alarm clock goes off in the morning

**Comment by partouf** [comment]
These are now all built

**Comment by lenary** [comment]
I *think* this is ready to be merged. I just checked it in my setup, and all these versions now download and run successfully when I pass `--version` to the clang binary. Next up: adding the config in the main CE repo, which I will do soon.

**Comment by partouf** [comment]
These should be installed during the night, will check tomorrow. Thanks!

**Pull request merged**
