### PR TITLE
Add library clad (clang plugin)

### PR DESCRIPTION
**Pull request by Vipul-Cariappa**
Clad is a source-transformation automatic differentiation (AD) library for C++,
implemented as a plugin for the Clang compiler.
Source at https://github.com/vgvassilev/clad

### CODE REVIEW

**Comment by partouf** [comment]
Think this looks ok, we'll have to try it out.

Can you submit it to https://github.com/compiler-explorer/compiler-explorer as well?

**Comment by Vipul-Cariappa** [comment]
@partouf, You can find the PR at https://github.com/compiler-explorer/compiler-explorer/pull/7109

**Comment by partouf** [comment]
I have reverted this change, Clad relies on a built version of the LLVM library, we don't have that available (only headers).

**Comment by vgvassilev** [comment]
I am confused. Clad requires as much build time and runtime dependencies as clang. Can you paste the error you see?

**Comment by partouf** [comment]
```
CMake Error at CMakeLists.txt:93 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by partouf** [comment]
https://github.com/compiler-explorer/clang-builder/blob/main/build/build.sh

**Comment by vgvassilev** [comment]
> https://github.com/compiler-explorer/clang-builder/blob/main/build/build.sh

I see. I think if we add an optional step after clang is built it should be able to build just fine. We will need to provide the `-DLLVM_DIR=<build/folder/of/clang>`. Alternatively we can do `-DLLVM_EXTERNAL_PROJECTS=clad -DLLVM_EXTERNAL_CLAD_SOURCE_DIR=<path>` but v1.7 does not seem to support that.

**Pull request merged**
