### PR TITLE
Add the github ureact library to the live site

### PR DESCRIPTION
**Pull request by YarikTH**
Proposing to add the µReact library to the live site. https://github.com/YarikTH/ureact

Followed the steps as best as I could in https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md#adding-a-new-library-to-the-live-site

Feedback on improving the hooks and the organizations of files in the repository is welcome.

See also https://github.com/compiler-explorer/compiler-explorer/pull/5339

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]

**Comment by mattgodbolt** [comment]
Thanks!

**Comment by mattgodbolt** [comment]
Just so you know - in this current form this won't update. The "versions" are `main` and a`dev` and don't get updated daily. I am not sure if that's what you wanted.

**Comment by YarikTH** [comment]
> Just so you know - in this current form this won't update. The "versions" are `main` and a`dev` and don't get updated daily. I am not sure if that's what you wanted. If that's not what you wanted then you'll need to look at one of the examples that is guarded under `if: nightly` and has a `nightlyclone` method. The `github` type downloads a github-released tagged version.

* main - is the stable trunk branch. It is always pointing to the latest release.
* dev - is a volatile development branch on which I check stuff for new release

I don't want to add real versions now, till 1.0. Because I rethink the API almost every release and old releases become obsolete.

So, as I understood, named github branches are cloned exactly once? How about trunk? I've seen it literally for every library. Is it the default branch with auto update policy?

**Comment by mattgodbolt** [comment]
> So, as I understood, named github branches are cloned exactly once? How about trunk? I've seen it literally for every library. Is it the default branch with auto update policy?

For the type `github`, that's correct.

If you need a branch that's updated every night, you need `nightlyclone`, and it needs to be guarded by an `if: nightly`.

**Pull request merged**
