### PR TITLE
Add spdlog (see compiler-explorer/compiler-explorer#2210)

### PR DESCRIPTION
**Pull request by mattgodbolt**
My first foray into using the new library.yaml!! :) There _is_ a cmake build too but if I used `build_type: cmake` nothing happened. As it's also header-only I left it; how might I add it to conan so that we can link against it too?

TIA!!

### CODE REVIEW

**Comment by partouf** [comment]
I suggest to set it explicitly to build_type: none if you really want to disable it, there are some built in mechanisms that enable building if it sees for example a CMakeLists.txt

I see that there is a static or shared library option here https://github.com/gabime/spdlog/blob/v1.x/CMakeLists.txt#L140
So I'm a bit confused about it now, is it header-only, or does it need building...

Either way, if you want to test out the building of the static library, you can check here https://github.com/compiler-explorer/compiler-explorer/blob/master/docs/internal/AddingLinkableLibrary.md
The `make_targets` should probably be `spdlog` as the CMakeLists says on line 140

**Comment by mattgodbolt** [comment]
So! I checked in a build, and the library does indeed build (yay!) Your instructions are _amazing_ though I don't know how to test linking locally.

It seems: if you build locally with CMake, then the CMake magic means that `-DSPDLOG_COMPILED_LIB` gets set during build which #ifdefs out a TON of slow-to-compile code (as it's compiled into the `.a` instead). Do you have a Cunning Idea how we might force `-DSPDLOG_COMPILED_LIB` in? It's the difference between a 22s compile and 4s compile when using the lib.

Thanks!!

**Comment by partouf** [comment]
> So! I checked in a build, and the library does indeed build (yay!) Your instructions are _amazing_ though I don't know how to test linking locally.
> 
> It seems: if you build locally with CMake, then the CMake magic means that `-DSPDLOG_COMPILED_LIB` gets set during build which #ifdefs out a TON of slow-to-compile code (as it's compiled into the `.a` instead). Do you have a Cunning Idea how we might force `-DSPDLOG_COMPILED_LIB` in? It's the difference between a 22s compile and 4s compile when using the lib.
> 
> Thanks!!

Hmm, I thought there was a way to add extra cmake arguments (https://github.com/compiler-explorer/infra/blob/7efd0887cf9497f951fff0f66e1176668d318f63/bin/lib/library_builder.py#L275), but it seems like its not something you can transmit through the yaml.
So maybe that's a thing to add.

**Comment by partouf** [comment]
Oh, or wait, is this a CE side kind of define that's needed?
Don't think there's anything for that either...

**Comment by mattgodbolt** [comment]
It's CE side: the same spdlog code is both "compile into a static lib" and "single header". So the way spdlog works is if you include it with `-DSPDLOG_COMPILED_LIB` it disables tons of code and expects to link against it instead.

**Comment by mattgodbolt** [comment]
(we can of course link this as-is; and as a workaround get folks using it to pass `-D...` manually, but it's something the magic of the CMakeLists.txt that spdlog uses does "magically". Took me a while to figure it out...ugh magic)

**Pull request merged**
