### PR TITLE
add clang-rocm 6.0.2 and 6.1.2

### PR DESCRIPTION
**Pull request by yxsamliu**
depends on https://github.com/compiler-explorer/clang-builder/pull/63

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Building these now; thanks...

**Comment by mattgodbolt** [comment]
6.0.2 succeeded: https://github.com/compiler-explorer/infra/actions/runs/9557720256
6.1.2 failed : https://github.com/compiler-explorer/infra/actions/runs/9557722583

**Comment by mattgodbolt** [comment]
6.1.2 error:
```
2024-06-18T02:18:16.9635513Z [6000/6974] Building CXX object tools/llvm-xray/CMakeFiles/llvm-xray.dir/xray-fdr-dump.cpp.o
2024-06-18T02:18:17.0059352Z [6001/6974] Generating source/reloc1.o
2024-06-18T02:18:17.0205258Z [6002/6974] Generating source/reloc-asm.o
2024-06-18T02:18:17.0206887Z clang-17: warning: argument unused during compilation: '-nogpulib' [-Wunused-command-line-argument]
2024-06-18T02:18:17.0555042Z [6003/6974] Generating source/source1.bc
2024-06-18T02:18:17.0557161Z FAILED: tools/comgr/test/source/source1.bc /root/build/tools/comgr/test/source/source1.bc 
2024-06-18T02:18:17.0561394Z cd /root/build/tools/comgr/test && /root/build/bin/clang-17 -c -emit-llvm -target amdgcn-amd-amdhsa -mcpu=gfx900 /root/llvm-project/amd/comgr/test/source/source1.cl -o source/source1.bc
2024-06-18T02:18:17.0565549Z clang-17: error: cannot find ROCm device library; provide its path via '--rocm-path' or '--rocm-device-lib-path', or pass '-nogpulib' to build without ROCm device library
2024-06-18T02:18:17.1368781Z [6004/6974] Building CXX object tools/llvm-reduce/CMakeFiles/llvm-reduce.dir/deltas/ReduceRegisterDefs.cpp.o
2024-06-18T02:18:17.1878668Z [6005/6974] Building CXX object tools/llvm-remark-size-diff/CMakeFiles/llvm-remark-size-diff.dir/RemarkSizeDiff.cpp.o
2024-06-18T02:18:17.2693935Z [6006/6974] Building CXX object tools/llvm-profgen/CMakeFiles/llvm-profgen.dir/PerfReader.cpp.o
2024-06-18T02:18:17.3614763Z [6007/6974] Linking CXX executable bin/llvm-ifs
2024-06-18T02:18:17.3902316Z [6008/6974] Building CXX object tools/llvm-reduce/CMakeFiles/llvm-reduce.dir/deltas/ReduceInstructionsMIR.cpp.o
```

**Review by mattgodbolt — CHANGES_REQUESTED** [review]
We either need to fix the rocm build or remove 6.1.2 here. I don't have any expertise on the rocm build; so will be looking to you to run and test the docker build locally and submit an appropirate fix there, if you choose to keep working on 6.1.2. thanks

**Comment by yxsamliu** [comment]
> We either need to fix the rocm build or remove 6.1.2 here. I don't have any expertise on the rocm build; so will be looking to you to run and test the docker build locally and submit an appropirate fix there, if you choose to keep working on 6.1.2. thanks

I think the clang build script has issue. I will take a look. Thanks.

**Comment by mattgodbolt** [comment]
> I think the clang build script has issue. I will take a look. Thanks.

Thank you!

**Comment by yxsamliu** [comment]
I got a fix for the failure https://github.com/compiler-explorer/clang-builder/pull/64

**Comment by mattgodbolt** [comment]
Building now! thanks... https://github.com/compiler-explorer/infra/actions/runs/9590802167

**Review by mattgodbolt — APPROVED** [review]
Fantastic: thanks!

**Comment by mattgodbolt** [comment]
This has installed now. Is there a PR configuring this in the compiler-explorer repo?

**Comment by yxsamliu** [comment]
> This has installed now. Is there a PR configuring this in the compiler-explorer repo?

I will open one. I think we also need this PR https://github.com/compiler-explorer/misc-builder/pull/84 before we can add them to compiler explorer.

**Pull request merged**
