### PR TITLE
Add erlang 26.2.2

### PR DESCRIPTION
**Pull request by treere**
As in title. The building process of erlang in the same of version 24

### CODE REVIEW

**Comment by partouf** [comment]
Looking at https://www.erlang.org/patches/otp-26.2.2 you did actually mean 26.2.2
You committed 26.1.2, can you change that?

**Comment by partouf** [comment]
the version will also need to be added to https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/erlang.amazon.properties

**Comment by partouf** [comment]
I have built the erlang version https://github.com/compiler-explorer/infra/actions/runs/7973235490

**Comment by treere** [comment]
> Looking at https://www.erlang.org/patches/otp-26.2.2 you did actually mean 26.2.2 You committed 26.1.2, can you change that?

Oh, thanks

**Comment by partouf** [comment]
version installed without problems

**Pull request merged**
