### PR TITLE
Add jsoncons

### PR DESCRIPTION
**Pull request by tomlankhorst**
> A C++, header-only library for constructing JSON and JSON-like data formats, with JSON Pointer, JSON Patch, JSON Schema, JSONPath, JMESPath, CSV, MessagePack, CBOR, BSON, UBJSON 

https://github.com/danielaparker/jsoncons

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Looks good - thanks. If you'd like it to appear in the list of libraries we'll need a second PR to the compiler-explorer/compiler-explorer repo to add it. Some tips at: https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md

**Comment by mattgodbolt** [comment]
This installed just fine:

```
Mar/08 03:05 admin-node~/infra (main|✔) 0.6s $ sudo ce_install install jsoncons
2022-03-08 03:05:51,635 lib.installation INFO     Making uncached requests
Installing libraries/c++/jsoncons 0.168.3
2022-03-08 03:05:54,295 lib.installation INFO     Fetching https://github.com/danielaparker/jsoncons/archive/v0.168.3.tar.gz (0 bytes)
2022-03-08 03:05:54,494 lib.installation INFO     100% of https://github.com/danielaparker/jsoncons/archive/v0.168.3.tar.gz
2022-03-08 03:05:54,494 lib.installation INFO     Piping to tar zxf -
2022-03-08 03:06:20,654 lib.installation INFO     Moving from staging (/opt/compiler-explorer/staging/jsoncons-0.168.3) to final destination (/opt/compiler-explorer/libs/jsoncons/v0.168.3)
2022-03-08 03:06:20,673 lib.installation INFO     libraries/c++/jsoncons 0.168.3 installed OK
1 packages installed OK, 0 skipped, and 0 failed installation
Mar/08 03:06 admin-node~/infra (main|✔) 29.6s $ ls /opt/compiler-explorer/libs/jsoncons/v0.168.3
CHANGELOG.md  CMakeLists.txt  LICENSE  README.md  Roadmap.md  acknowledgements.md  appveyor.yml.bak  cmake/  doc/  examples/  examples_boost/  fuzzers/  include/  tests/  third_party/
```

**Comment by tomlankhorst** [comment]
Thank you! I'll create a PR for that too.

**Comment by mattgodbolt** [comment]
Apologies, I spotted a typo : #5239 - so this isn't working quite as hoped. Will be merged and will be in the next release.

**Pull request merged**
