### PR TITLE
GCC 11.2

### PR DESCRIPTION
**Pull request by ojeda**
CE: https://github.com/compiler-explorer/compiler-explorer/pull/2822

### CODE REVIEW

**Comment by partouf** [comment]
Compilation for GCC 11.2.0 is failing, but I can't figure out Why exactly'
https://godbolt.org/admin/logs/gcc_1120

**Comment by apmorton** [comment]
```
../../../../gcc-11.2.0/libgo/runtime/proc.c: In function 'runtime_gogo':
../../../../gcc-11.2.0/libgo/runtime/proc.c:293:9: error: implicit declaration of function 'fixcontext'; did you mean 'setcontext'? [-Werror=implicit-function-declaration]
  293 |         fixcontext(ucontext_arg(&newg->context[0]));
      |         ^~~~~~~~~~
      |         setcontext
../../../../gcc-11.2.0/libgo/runtime/proc.c: In function 'runtime_mstart':
../../../../gcc-11.2.0/libgo/runtime/proc.c:558:9: error: implicit declaration of function 'initcontext'; did you mean 'setcontext'? [-Werror=implicit-function-declaration]
  558 |         initcontext();
      |         ^~~~~~~~~~~
      |         setcontext
      ```

**Comment by ojeda** [comment]
The error seems to be that `SETCONTEXT_CLOBBERS_TLS` is set, which would hint at the configure test failing. Nothing seems to have changed lately around this (from a quick look, at least).

Has something changed in the environment you are building? For instance, someone hit this due to Docker blocking the `sigprocmask` syscall: https://github.com/docker-library/gcc/issues/38#issuecomment-405731074. Otherwise, perhaps try to see why the test program is failing:

```c
#include <pthread.h>
#include <stdlib.h>
#include <ucontext.h>
#include <unistd.h>

__thread int tls;

static char stack[10 * 1024 * 1024];
static ucontext_t c;

/* Called via makecontext/setcontext.  */

static void
cfn (void)
{
  exit (tls);
}

/* Called via pthread_create.  */

static void *
tfn (void *dummy)
{
  /* The thread should still see this value after calling
     setcontext.  */
  tls = 0;

  setcontext (&c);

  /* The call to setcontext should not return.  */
  abort ();
}

int
main ()
{
  pthread_t tid;

  /* The thread should not see this value.  */
  tls = 1;

  if (getcontext (&c) < 0)
    abort ();

  c.uc_stack.ss_sp = stack;
#ifdef MAKECONTEXT_STACK_TOP
  c.uc_stack.ss_sp += sizeof stack;
#endif
  c.uc_stack.ss_flags = 0;
  c.uc_stack.ss_size = sizeof stack;
  c.uc_link = NULL;
  makecontext (&c, cfn, 0);

  if (pthread_create (&tid, NULL, tfn, NULL) != 0)
    abort ();

  if (pthread_join (tid, NULL) != 0)
    abort ();

  /* The thread should have called exit.  */
  abort ();
}
```

**Comment by partouf** [comment]
> What was the problem in the end? Docker?

Probably, it got solved when I upgraded the host from Ub18 to 20 (had to rebuild the instance from scratch due to other reasons, but was based on a really old version of our builder)

**Comment by ojeda** [comment]
Thanks!

**Pull request merged**
