### PR TITLE
Add Go 1.21

### PR DESCRIPTION
**Pull request by DmitriyMV**
Prepare for compiler-explorer update.

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Comment by mattgodbolt** [comment]
This failed to install:
```
2023-08-15 03:17:22,946 lib.ce_install  INFO     compilers/go/golang 1.21 failed to install: Fetch failure for https://storage.googleapis.com/golang/go1.21.linux-amd64.tar.gz: <Response [404]>
Traceback (most recent call last):
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 393, in install
    installable.install()
  File "/home/ubuntu/infra/bin/lib/installable/archives.py", line 195, in install
    self.stage(staging)
  File "/home/ubuntu/infra/bin/lib/installable/archives.py", line 176, in stage
    self.install_context.fetch_url_and_pipe_to(staging, f"{self.url}", self.tar_cmd, self.untar_to)
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 143, in fetch_url_and_pipe_to
    self.fetch_to(url, fd, agent)
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 118, in fetch_to
    raise FetchFailure(f"Fetch failure for {url}: {request}")
lib.installation_context.FetchFailure: Fetch failure for https://storage.googleapis.com/golang/go1.21.linux-amd64.tar.gz: <Response [404]>
```

**Comment by mattgodbolt** [comment]
I'm going to revert this change: can you PR with the fixed URL once you know what it is, or ping me here if you need assistance in testing locally.

**Comment by DmitriyMV** [comment]
@mattgodbolt they changed version scheme. [This](https://github.com/compiler-explorer/infra/pull/1073) should work.

**Comment by mattgodbolt** [comment]
Perfect: merged the other and will try and look at this tonight. thanks for your patience

**Pull request merged**
